/* Browser captures of the playable application. Actions use visible controls. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'previews/episode');fs.mkdirSync(out,{recursive:true});
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mmt-episode-capture-'));
const localChrome=path.join(os.homedir(),'Library/Caches/ms-playwright/chromium_headless_shell-1194/chrome-mac/headless_shell');
const base=process.env.MMT_PREVIEW_URL||'http://127.0.0.1:8769/Design/episode-01/index.html';
(async()=>{const browser=await chromium.launch({executablePath:process.env.MMT_CHROMIUM||(fs.existsSync(localChrome)?localChrome:undefined),headless:true});const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1,reducedMotion:'reduce'}),p=await context.newPage(),errors=[],checks=[],entries=[],sequences=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>!!window.MMTGame);await p.evaluate(()=>document.fonts.ready);
const state=()=>p.evaluate(()=>MMTGame.state),click=(sel)=>p.locator(sel).click(),tick=async(n=1)=>{for(let i=0;i<n;i++)await click('#advance');};
async function camera(){await p.evaluate(()=>window.scrollTo(0,document.querySelector('.dashboard').offsetTop-16));}
async function still(id,title,caption,selector=null){if(!selector)await camera();const file=path.join(out,id+'.png');if(selector)await p.locator(selector).screenshot({path:file});else await p.screenshot({path:file});entries.push({id:'episode-'+id,title,png:'episode/'+id+'.png',gif:'episode/'+id+'.gif',kind:'still',group:'Episode',route:'#episode/playable-episode',caption,size:selector?null:[1440,1080]});return file;}
let sequence;
async function begin(id,title,caption){sequence={id:'episode-'+id,title,caption,frames:[],actions:[],temp:path.join(tmp,id)};fs.mkdirSync(sequence.temp);}
async function frame(label,hold=1200,selector=null){await p.evaluate(()=>MMTGame.setSceneTime(MMTGame.state.turn*1.7));if(!selector)await camera();const file=path.join(sequence.temp,String(sequence.frames.length).padStart(3,'0')+'.png');if(selector)await p.locator(selector).screenshot({path:file});else await p.screenshot({path:file});sequence.frames.push({file,duration:hold,label,turn:(await state()).turn});}
async function end(){const s=await state();sequence.actions=s.actions;sequence.outcome=await p.evaluate(()=>MMTEpisode.outcome(MMTGame.state));fs.writeFileSync(path.join(out,sequence.id.replace('episode-','')+'-run.json'),JSON.stringify({scope:'Fictional UI playthrough; capture timing condensed',state:s,outcome:sequence.outcome},null,2)+'\n');sequences.push(sequence);}
// Full supplier route: real buttons, read a saved record, trace, request permission, reissue.
await begin('supplier-run','Supplier run / return to handoff','Actual UI playthrough, condensed. P-04 returns; a trace and approval lead to P-05. Friday handoff is accepted.');
await click('[data-action="plan"][data-value="supplier"]');await still('planning','Choose the production plan','C-07 supplier plan before commitment. Budget, posted cash and reservations stay separate.');await frame('Plan S-08',1600);await tick(2);await frame('Tuesday debit',1600);
await click('[data-doc="v2"]');await still('paid-record','Saved Paid record','Tuesday v2 predates the Wednesday return. The saved record is never rewritten.','#desk');await frame('Read Tuesday v2',2000,'#desk');const beforeRead=await state();await p.waitForTimeout(200);assert.equal((await state()).turn,beforeRead.turn);await click('#close-desk');checks.push({name:'Document reading pauses time and preserves selection',passed:true});
await tick(2);assert.equal((await state()).returned,true);await click('[data-view="Information"]');await still('return','One attempt, three states','Wednesday: returned funding, a Tuesday Paid snapshot and an unresolved obligation.');await frame('Wednesday return',2000);
await click('[data-doc="bank"]');await still('bank-record','Bank-event strip','The $12,000 debit and return net to zero for P-04; the obligation remains open.','#desk');await frame('Read bank extract',1800,'#desk');await click('#close-desk');
await click('[data-action="request"][data-value="processor"]');await click('[data-action="request"][data-value="delay"]');await tick();await frame('Trace received; Friday agreed',1800);await click('[data-action="request"][data-value="approval"]');await tick();await click('[data-view="Control"]');await still('authority','Authority before reissue','The producer requests; finance authorizes one new attempt against O-19.');await frame('Finance permission',1800);await click('[data-action="reissue"]');await frame('P-05 debited',1600);await tick();await click('[data-view="Work"]');await frame('Recipient confirms; handoff next',1800);await tick(2);await click('[data-action="poolAnswer"][data-value="200000"]');assert.equal((await state()).delivered,8);await still('outcome','Supplier run / outcome','The revised promise is kept; the original Thursday promise is missed. The client invoice is still a receivable.','#outcome');await frame('Outcome',2400,'#outcome');await end();checks.push({name:'Full supplier UI route completes with Friday AM delivery and $20,000 posted cash',passed:(await state()).cash===2000000});
// Downloads and replay/resume are tested from the live interface.
const dl=p.waitForEvent('download');await click('#export-run');const download=await dl;await download.saveAs(path.join(tmp,'download.json'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(tmp,'download.json'))).state,await state());checks.push({name:'Run receipt downloads the exact current state',passed:true});
const saved=await state();await p.reload();await p.waitForFunction(()=>!!window.MMTGame);assert.deepEqual(await state(),saved);checks.push({name:'Reload replays and restores committed state',passed:true});
// Internal route preserves the competing job before concentrating resources.
await click('[data-action="replay"]');await begin('internal-run','In-house run / staffing and handoff','Actual UI playthrough, condensed. Three shared intervals protect the display job; concentrated staffing then meets Thursday. No supplier attempt is created.');await frame('Internal plan',1800);await tick(3);await click('[data-view="People"]');await frame('Display reservation protected',1800);await click('[data-action="crew"][data-value="2"]');await tick(3);await click('[data-view="Work"]');await still('fabrication','Production before handoff','The component is fabricated and packed. Physical handoff takes a further interval.');await frame('Ready at the near-dock bay',2000);await click('[data-action="crew"][data-value="1"]');await tick(3);await frame('Internal outcome',2400,'#outcome');assert.equal((await state()).delivered,7);assert.equal((await state()).ledger.some(e=>e.id==='P-04-debit'),false);await end();checks.push({name:'In-house UI route completes on Thursday without creating a supplier obligation',passed:true});
// Ordinary supplier control has no return.
await click('[data-action="ordinary"]');await click('[data-action="plan"][data-value="supplier"]');await begin('ordinary-run','Ordinary supplier / valid control','Actual UI playthrough, condensed. P-04 is received normally. B-09 is one bank payment with two supported allocations.');await frame('Ordinary supplier plan',1600);await tick(3);await frame('Receipt confirms release',1800);await tick(3);await click('[data-doc="pool"]');await still('pool-record','One debit, two allocations','Routine batch B-09 includes both recipient receipts. Allocations do not create extra cash movements.','#desk');await frame('Read valid batch',2200,'#desk');await click('#close-desk');await tick(3);await click('[data-action="poolAnswer"][data-value="200000"]');await frame('Ordinary outcome',2200,'#outcome');assert.equal((await state()).returned,false);await end();checks.push({name:'Ordinary supplier UI run has a confirmed receipt and no manufactured anomaly',passed:true});
// Alternate response, five views and static export; scenery sampled from the live canvas.
await click('[data-action="replay"]');await click('[data-action="plan"][data-value="supplier"]');await p.selectOption('#mode','episode');await click('[data-action="plan"][data-value="supplier"]');await tick(4);await click('[data-action="substitute"]');await click('[data-action="crew"][data-value="2"]');await tick(2);await begin('five-views','Five views / same project','Same turn and selected project across Work, Cash, Information, Control and People. Fictional substitute route.');for(const v of ['Work','Cash','Information','Control','People']){await click(`[data-view="${v}"]`);await frame(v,2000);assert.equal((await state()).turn,6);assert.equal((await state()).selection,'C-07');}await end();checks.push({name:'Five views preserve time and object identity',passed:true});await click('[data-view="Work"]');await tick(3);assert.equal((await state()).delivered,7);assert.equal((await state()).supplierSettled,false);await still('substitute-outcome','Substitute run / open obligation','Thursday delivery is met, while $12,000 remains reserved for O-19. New production is not a settlement.','#outcome');checks.push({name:'Substitute UI path protects delivery while preserving the original obligation',passed:true});
await click('[data-action="replay"]');await tick(2);const anim={id:'episode-map-cycle',title:'Workshop / scenery cycle',caption:'36-second scene sample from the running canvas, with production state held at Tuesday AM. Staff, courier and cat use the shared original renderers.',temp:path.join(tmp,'map-cycle'),frames:[],actions:[]};fs.mkdirSync(anim.temp);for(let i=0;i<180;i++){await p.evaluate(time=>MMTGame.setSceneTime(time),i/5);const data=await p.locator('#map').evaluate(c=>c.toDataURL('image/png').split(',')[1]),file=path.join(anim.temp,String(i).padStart(3,'0')+'.png');fs.writeFileSync(file,Buffer.from(data,'base64'));anim.frames.push({file,duration:200,label:'Scenery at '+i/5,turn:2});}sequences.push(anim);
// The secondary selection must describe its own work, not inherit O-19's fields.
await click('[data-select="OTHER"]');for(const v of ['Work','Cash','Information','Control','People']){await click(`[data-view="${v}"]`);assert.match(await p.locator('#view-panel').innerText(),/Display job/);}checks.push({name:'The competing job has its own context in all five views',passed:true});
// Narrow and keyboard checks.
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:path.join(root,'qa/episode-390.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push({name:'390px layout has no horizontal page overflow',passed:true});await click('[data-doc="terms"]');await p.keyboard.press('Escape');assert.equal(await p.locator('#desk').evaluate(e=>e.open),false);checks.push({name:'Document dialog closes with Escape',passed:true});
// Keyboard activation preserves the newly rendered plan button's focus.
await p.evaluate(()=>MMTGame.reset('ordinary'));await p.locator('[data-action="plan"][data-value="internal"]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.dataset.value),'internal');checks.push({name:'Keyboard plan selection retains focus after rendering',passed:true});
// Fresh desktop still and a native file URL smoke test.
await p.setViewportSize({width:1440,height:1080});await p.goto('file://'+path.join(root,'episode-01/index.html'));await p.waitForFunction(()=>!!window.MMTGame);checks.push({name:'Standalone file URL starts without a server',passed:true});assert.deepEqual(errors,[]);checks.push({name:'No browser script errors during playthroughs',passed:true});
const sources=['episode-01/model.js','episode-01/episode.js','episode-01/episode.css','episode-01/scene.js','episode-01/index.html','working/pixel-kit.js','working/park-kit.js'].map(f=>({file:'../../'+f,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')}));fs.writeFileSync(path.join(__dirname,'episode-capture-input.json'),JSON.stringify({output:out,entries,sequences,temp:tmp,sources},null,2));fs.writeFileSync(path.join(root,'qa/episode-browser-checks.json'),JSON.stringify({viewport:[1440,1080],mobile:[390,844],checks,errors,passed:true},null,2)+'\n');await browser.close();console.log(JSON.stringify({stills:entries.length,sequences:sequences.length,checks:checks.length,temp:tmp}));})().catch(e=>{console.error(e);process.exit(1)});
