const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('../episode-01/model.js');
const checks=[];function test(name,fn){fn();checks.push({name,passed:true});}
const act=(s,type,value)=>E.reduce(s,{type,value}),tick=(s,n=1)=>{for(let i=0;i<n;i++)s=act(s,'advance');return s;};
function start(plan='supplier',mode='episode',bay='dock'){let s=E.initial(mode);s=act(s,'plan',plan);return act(s,'bay',bay);}
function finish(s){while(!s.finished)s=tick(s);return s;}
test('Internal and supplier plans both work in the ordinary control',()=>{let a=start('internal','ordinary');a=tick(a,3);a=act(a,'crew',2);a=tick(a,3);a=act(a,'crew',1);a=finish(a);assert.equal(a.delivered,7);assert.equal(a.otherDone,3);assert.equal(a.cash,2800000);assert.equal(a.ledger.some(x=>x.id==='P-04-debit'),false);let b=finish(start('supplier','ordinary'));assert.equal(b.delivered,4);assert.equal(b.otherDone,3);assert.equal(b.cash,2000000);assert.equal(b.supplierSettled,true);});
test('Bay placement changes physical handoff, concentrated staffing can miss a reservation',()=>{let a=start('internal','ordinary','studio');a=tick(a,3);a=act(a,'crew',2);a=finish(a);assert.equal(a.delivered,8);assert.equal(a.otherDone,3);let b=start('internal');b=act(b,'crew',2);b=tick(b,4);b=act(b,'crew',1);b=finish(b);assert.equal(b.delivered,5);assert.equal(b.otherDone,7);assert.equal(E.outcome(b).otherOnTime,false);});
test('Returned funding restores cash but not settlement; saved Tuesday label remains',()=>{const s=tick(start(),4);assert.equal(s.cash,4000000);assert.equal(s.supplierSettled,false);assert.equal(E.committed(s),2000000);assert.ok(s.documents.includes('v2'));assert.equal(s.ledger.filter(x=>x.id.startsWith('P-04')).reduce((n,x)=>n+x.amount,0),0);assert.throws(()=>act(s,'reissue'));assert.throws(()=>act(s,'request','approval'));});
test('New payment requires authority, debits only once, and closes on recipient confirmation',()=>{let s=tick(start(),4);s=act(s,'request','processor');s=act(s,'request','delay');s=tick(s);s=act(s,'request','approval');s=tick(s);s=act(s,'reissue');assert.equal(s.supplierSettled,false);assert.throws(()=>act(s,'reissue'));s=tick(s);assert.equal(s.supplierSettled,true);assert.equal(s.delivered,null);s=finish(s);assert.equal(s.delivered,8);assert.equal(s.cash,2000000);assert.equal(E.outcome(s).metPromise,true);assert.equal(E.outcome(s).originalPromiseMet,false);assert.equal(s.promise,9);});
test('Substitute can protect delivery while the original obligation remains reserved',()=>{let s=tick(start(),4);s=act(s,'substitute');s=act(s,'crew',2);s=tick(s,2);s=act(s,'crew',1);s=finish(s);assert.equal(s.delivered,7);assert.equal(s.cash,2650000);assert.equal(E.committed(s),1200000);assert.equal(E.available(s),1450000);assert.equal(s.supplierSettled,false);assert.equal(s.otherDone,3);});
test('Routine batch is one debit; its allocations are not additional cash movements',()=>{let s=finish(start('internal'));s=act(s,'poolAnswer',200000);assert.match(E.outcome(s).batch,/correctly/);assert.equal(s.ledger.filter(x=>x.id==='B-09').length,1);s=act(s,'poolAnswer',400000);assert.match(E.outcome(s).batch,/not yet/);});
test('Rejected transitions do not mutate state; action replay recreates the complete run',()=>{let s=tick(start(),4),original=JSON.stringify(s);assert.throws(()=>act(s,'plan','internal'));assert.equal(JSON.stringify(s),original);s=act(s,'substitute');s=finish(s);const replay=s.actions.reduce((state,a)=>E.reduce(state,a),E.initial(s.mode));assert.deepEqual(replay,s);assert.equal(s.cash,E.CONFIG.startingCash+s.ledger.reduce((n,x)=>n+x.amount,0));assert.throws(()=>act(s,'advance'));assert.throws(()=>act(E.initial(),'plan','unknown'));});
const out={schema:1,scope:'Fictional deterministic simulation; automated checks do not validate learning or historical binding',checks,passed:true};fs.writeFileSync(path.join(__dirname,'../qa/episode-engine-checks.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
