import fs from 'node:fs';
import { invoiceSheet, bankSheet } from './document-materials.mjs';
const asset='assets/sprite-catalogue/';
const manifest=JSON.parse(fs.readFileSync(new URL('../assets/sprite-catalogue/manifest.json',import.meta.url)));
const objectImage=(id,title)=>{const o=manifest.objects.find(o=>o.id===id),v=o.variants[0],b=v.bounds,k=Math.max(1,Math.min(3,Math.floor(220/b.width),Math.floor(160/b.height)));return `<img src="${asset}${v.file}" alt="${title}" class="pixel-preview" loading="lazy" style="position:absolute;width:${o.size[0]*k}px;height:${o.size[1]*k}px;max-width:none;max-height:none;left:calc(50% - ${(b.x+b.width/2)*k}px);top:calc(50% - ${(b.y+b.height/2)*k}px)">`};
const plate=(id,title,body,caption)=>`<figure class="plate editorial-plate" id="fig-${id}"><figcaption><span class="figure-id">${id}</span><strong>${title}</strong></figcaption>${body}<div class="figure-note">${caption}</div></figure>`;
const image=(src,alt,pixel=true)=>`<img src="${src}" alt="${alt}" class="${pixel?'pixel-preview':''}" loading="lazy">`;
const object=(id,title,copy)=>`<a class="object-example" href="${asset}index.html#${id}"><span class="example-image">${objectImage(id,title)}</span><span class="example-copy"><small>ART OBJECT / ${id}</small><b>${title}</b><span>${copy}</span><em>Inspect object ↗</em></span></a>`;
const miniCopy=`<article class="mini-carbon"><span>PLATFORM / O-19</span><b>Payment record</b><dl><dt>Saved version</dt><dd>v2</dd><dt>Label</dt><dd>Paid</dd><dt>Effective</dt><dd>W3 Tue · 10:00</dd><dt>Recorded</dt><dd>W3 Tue · 10:02</dd></dl><p>The label belongs to this saved version.</p><small>FICTIONAL PRACTICE</small></article>`;
export const editorialFigures={
 'game-in-context':plate('D01','A place to operate; records to inspect',`<a class="scene-preview" href="#art/world-and-interface">${image('assets/art-system/campus.png','Current office-derived park: three sites around shared courts, paths and original landmarks')}<span>Explore the working art study ↗</span></a><div class="example-pair"><div><b>Built</b><p>Site selection, cutaways, courtyard layouts, landmark inspectors and linked practice records.</p></div><div><b>Next playable proof</b><p>Reserve capacity, run one handoff and see how the chosen plan changes delivery.</p><a href="#production/production-sequence">Build sequence →</a></div></div>`,`Current art and interaction proof. The arrangement is fictional; the production economy has not been implemented.`),
 'episode-documents':plate('D02','Three records of one fictional payment',`<div class="document-triptych"><a href="#art/interface-materials" aria-label="Open the invoice specimen"><div class="document-mini">${invoiceSheet()}</div><b>Obligation</b><span>What the agency owes.</span></a><a href="#art/interface-materials" aria-label="Open the carbon-copy specimen"><div class="document-mini">${miniCopy}</div><b>Saved platform state</b><span>What version 2 says.</span></a><a href="#art/interface-materials" aria-label="Open the bank-event specimen"><div class="document-mini">${bankSheet()}</div><b>Bank events</b><span>What moved in this extract.</span></a></div>`,`C-07 / O-19 / P-04 · Invented USD fixture. These are the same components opened by the separate Practice documents tray. <a href="#art/interface-materials">Open, compare and switch versions →</a>`),
 'object-examples':plate('D03','Artwork is a representation, not an identity',`<div class="object-examples">${object('B-02','Site · Porter hall','A place with capacity and access. Occupancy, departments and legal entities remain separate.')}${object('L-07','Scenery · reception','A recognisable furnishing. It carries no invented cash balance or authority.')}${object('PR-04','Vehicle · supplier visit','The van shows an arrival. The engagement, invoice and payment remain linked records.')}</div>`,`Art-library IDs identify drawings. Case claims, practice objects and legal entities use separate identities. A character’s shirt or a building’s colour does not establish a financial role.`),
 'narrative-sequence':plate('D04','Learning order',`<ol class="learning-sequence">${[
 ['01','Work','Make one job run','assets/art-system/props.png'],['02','Authority','Find the action’s actual gate','assets/art-system/icon-control.png'],['03','Reporting','Compare two representations','assets/art-system/icon-information.png'],['04','Payment','Follow an attempt and return','assets/art-system/icon-cash.png'],['05','Entities','Separate benefit from burden','assets/art-system/van.png'],['06','Handover','Keep identity across versions','assets/art-system/icon-information.png'],['07','After closing','Inspect the record afterlife','assets/art-system/icon-control.png']
].map(([n,t,d,src])=>`<li><span class="learning-number">${n}</span><div class="learning-image">${image(src,`${t} chapter illustration`)}</div><div><b>${t}</b><span>${d}</span></div></li>`).join('')}</ol>`,`Proposed chapter sequence. The illustrations use the current art kit; they do not depict historical events. The source chronology remains available separately.`),
 'current-deliverables':plate('D05','Current system',`<div class="deliverable-grid"><a href="assets/sprite-catalogue/index.html">${image('assets/sprite-catalogue/sheets/buildings-overview.png','Three building families from the current 44-object sprite library')}<b>Object library</b><span>44 objects · 121 frame slots<br>PNG, GIF, sheets and manifest ↗</span></a><a href="previews/index.html">${image('assets/art-system/campus-cutaway.png','Current scene with the selected roof removed')}<b>Preview library</b><span>Current scenes, components and motion<br>One place to inspect and download ↗</span></a><a href="#binding">${image('assets/zero-machine-page-34.png','Original Creative Peaks page in The Zero Machine',false)}<b>Source binding</b><span>Export fields inspected<br>Historical interaction inactive →</span></a></div>`,`The reader, previews and catalogue share the current art renderers and asset register. Historical binding has a separate source manifest. Superseded studies belong in the <a href="archive/index.html">versioned archive ↗</a>.`),
 'evidence-layers':plate('D06','Keep the source and the review separate',`<div class="evidence-example"><a href="../The_Zero_Machine_Specific_Story_Reconstruction%20FINAL.pdf#page=34">${image('assets/zero-machine-page-34.png','Unaltered source page 34 of The Zero Machine',false)}<span>CASE-01 · page 34 ↗</span></a><div><div class="evidence-layer"><small>SOURCE CLAIM</small><b>Return with Paid retained</b><span>The reconstruction’s account, with its page locator.</span></div><div class="evidence-layer"><small>INSPECTED MATERIAL</small><b>Selected export fields</b><span>BILL snapshots, bank extractions and QBO entries. Exact file hashes and row locators are retained.</span></div><div class="evidence-layer"><small>UNRESOLVED</small><b>Originals, links and endpoint</b><span>Return identity, October 23 bank direction, continuous status history and final recipient settlement remain open.</span></div><a href="#binding-inventory">Read the source inventory →</a></div></div>`,`A source’s conclusion and the project’s inspection status answer different questions. Publishing this design review does not activate historical gameplay.`)
};
export const readerPreviewLinks=`<div class="reader-preview-links"><a href="#art/world-and-interface">${image('assets/art-system/campus.png','Open the current park study')}<span>Park study ↗</span></a><a href="assets/sprite-catalogue/index.html">${image('assets/sprite-catalogue/sheets/buildings-overview.png','Open the object catalogue')}<span>Object catalogue ↗</span></a><a href="previews/index.html">${image('assets/sprite-catalogue/previews/boerum-street-poster.png','Open current previews and GIF downloads')}<span>Previews & downloads ↗</span></a></div>`;
