import { objectMedia, playbackButton } from './object-media.mjs';
const asset='assets/sprite-catalogue/';
const plate=(id,title,body,caption)=>`<figure class="plate editorial-plate" id="fig-${id}"><figcaption><span class="figure-id">${id}</span><strong>${title}</strong></figcaption>${body}<div class="figure-note">${caption}</div></figure>`;
const image=(src,alt,pixel=true)=>`<img src="${src==='assets/art-system/campus.png'?'previews/art-hero.png':src}" ${src==='assets/art-system/campus.png'?'data-motion-src="previews/art-hero.gif"':''} alt="${alt}" class="${pixel?'pixel-preview':''}" loading="lazy">`;
const object=(id,title,copy)=>`<a class="object-example" href="${asset}index.html#${id}"><span class="example-image">${objectMedia(id,{title,width:160,height:115})}</span><span class="example-copy"><small>${id}</small><b>${title}</b><span>${copy}</span><em>Inspect object ↗</em></span></a>`;
export const editorialFigures={
 'game-in-context':plate('D01','Park study and playable episode',`<div class="game-context"><a class="scene-preview" href="#art/world-and-interface">${image('assets/art-system/campus.png','Office-derived park with three sites, shared courts and original landmarks')}<span>Explore park →</span></a><div class="context-copy"><h4>Workshop prototype</h4><p>Episode 01 uses this art system for a workshop. Choose a production plan, allocate staff and respond to a returned payment.</p><a href="episode-01/index.html">Play Episode 01 ↗</a></div></div>`,`${playbackButton} The composite park is an art study. The episode runs a separate fictional production and payment model.`),
 'episode-documents':plate('D02','Three records of one payment',`<div class="record-extracts"><a class="record-extract extract-invoice" href="#art/interface-materials"><small>O-19 / INVOICE</small><h4>Fabrication</h4><strong>$12,000 <em>USD</em></strong><dl><dt>Supplier</dt><dd>S-08</dd><dt>Settlement</dt><dd>Not established</dd></dl><span>Inspect obligation →</span></a><a class="record-extract extract-carbon" href="#art/interface-materials"><small>O-19 / SAVED v2</small><h4>Paid</h4><dl><dt>Effective</dt><dd>Tue 10:00</dd><dt>Recorded</dt><dd>Tue 10:02</dd><dt>Attempt</dt><dd>P-04</dd></dl><span>Compare versions →</span></a><a class="record-extract extract-bank" href="#art/interface-materials"><small>P-04 / BANK EVENTS</small><div><span>Tue · debit</span><b>−12,000</b></div><div><span>Wed · return</span><b>+12,000</b></div><p>Later settlement<br><b>Not supplied</b></p><span>Read bank strip →</span></a></div>`,`Selected fields from the fictional USD fixture. The saved Paid record predates the return. <a href="#art/interface-materials">Open the full documents →</a>`),
 'object-examples':plate('D03','Sites, scenery and operating records',`<div class="object-examples">${object('B-02','Porter hall','A site supplies space and access. Occupants and departments have separate identities.')}${object('L-07','Reception desk','A furnishing drawn from office photography. No balance or approval authority is assigned to it.')}${object('PR-04','Supplier van','An arrival animation. The engagement, invoice and payment are linked records.')}</div>`,`${playbackButton} Art IDs identify drawings. Case claims, practice objects and legal entities have their own IDs.`),
 'current-deliverables':plate('D05','Current system',`<div class="deliverable-grid"><a href="assets/sprite-catalogue/index.html">${image('assets/sprite-catalogue/sheets/buildings-overview.png','Building families from the sprite library')}<b>Object library</b><span>44 objects · 136 frame slots<br>PNG, GIF, sheets and manifest ↗</span></a><a href="previews/index.html">${image('assets/art-system/campus-cutaway.png','Scene with the selected roof removed')}<b>Preview library</b><span>Scenes, components and motion<br>Inspect and download ↗</span></a><a href="#binding">${image('assets/zero-machine-page-34.png','Creative Peaks source page in The Zero Machine',false)}<b>Source binding</b><span>Export fields inspected<br>Historical interaction inactive →</span></a><a href="../test/index.html">${image('assets/art-system/campus.png','Park assets available in the standalone builder')}<b>Park builder</b><span>Place objects, people and events<br>Save locally and export GIFs ↗</span></a></div>`,`The reader, previews and catalogue use one asset register. Source binding has a separate manifest. <a href="archive/index.html">Superseded studies and documents ↗</a>`),
 'evidence-layers':plate('D06','Source claim and inspection status',`<div class="evidence-example"><a href="../The_Zero_Machine_Specific_Story_Reconstruction%20FINAL.pdf#page=34">${image('assets/zero-machine-page-34.png','Unaltered source page 34 of The Zero Machine',false)}<span>CASE-01 · p.34 ↗</span></a><div><div class="evidence-layer"><small>SOURCE CLAIM</small><b>Return with Paid retained</b><span>The reconstruction’s account, on page 34.</span></div><div class="evidence-layer"><small>INSPECTED MATERIAL</small><b>Selected export fields</b><span>BILL snapshots, bank extractions and QBO entries. File hashes and row locators identify the inspected records.</span></div><div class="evidence-layer"><small>UNRESOLVED</small><b>Originals, links and settlement</b><span>Return identity, October 23 bank direction, continuous status history and final recipient settlement remain open.</span></div><a href="#binding-inventory">Read the source inventory →</a></div></div>`,`The source claim exceeds what the inspected exports establish. Historical gameplay remains inactive.`)
};
export const readerPreviewLinks=`<div class="reader-preview-links"><a href="#art/world-and-interface">${image('assets/art-system/campus.png','Open the current park study')}<span>Park study ↗</span></a><a href="assets/sprite-catalogue/index.html">${image('assets/sprite-catalogue/sheets/buildings-overview.png','Open the object catalogue')}<span>Object catalogue ↗</span></a><a href="previews/index.html"><img src="assets/sprite-catalogue/previews/boerum-street-poster.png" data-motion-src="assets/sprite-catalogue/previews/boerum-street-loop.gif" alt="Boerum street animation · previews and downloads" class="pixel-preview" loading="lazy"><span>Previews & downloads ↗</span></a>${playbackButton}</div>`;
