const plate=(id,title,body,caption)=>`<figure class="plate episode-plate" id="fig-${id}"><figcaption><span class="figure-id">${id}</span><strong>${title}</strong></figcaption>${body}<div class="figure-note">${caption}</div></figure>`;
const shot=(file,title,body)=>`<a class="episode-shot" href="previews/episode/${file}.png" target="_blank"><span class="episode-shot-image"><img src="previews/episode/${file}.png" alt="${title}" loading="lazy"></span><span class="episode-shot-copy"><b>${title}</b><span>${body}</span><em>View capture ↗</em></span></a>`;
const gif=(id,label)=>`<a href="previews/episode/${id}.gif" download>${label} GIF ↓</a>`;
export const episodeFigures={
'episode-playable':plate('E01','C-07 / The handoff',`<a class="episode-launch" href="episode-01/index.html"><img src="previews/episode/planning.png" alt="The running episode: workshop map, plan selection, staffing and separate cash measures"><span><b>Play Episode 01 ↗</b><small>Full exception route + ordinary control</small></span></a><div class="episode-downloads">${gif('supplier-run','Supplier playthrough')}${gif('internal-run','In-house playthrough')}<a href="previews/index.html#episode">All captures & run receipts →</a></div>`,`Complete fictional loop, tested through the browser. The 12–15 minute session length is a design target, not a measured participant result. All operating values are invented; historical comparison remains read-only.`),
'episode-branches':plate('E02','Two plans; different consequences',`<a class="episode-diagram" href="previews/episode/decision-map.svg" target="_blank"><img src="previews/episode/decision-map.svg" alt="In-house staffing reaches Thursday without O-19; the supplier return branches into an approved reissue or a substitute" loading="lazy"></a>`,`Paths shown were run through the executable model. They assume near-dock placement and shared staffing through Tuesday. <a href="previews/episode/decision-map.svg" download>Diagram SVG ↓</a> · <a href="previews/episode/decision-map.gif" download>Still GIF ↓</a>`),
'episode-storyboard':plate('E03','The episode, as played',`<div class="episode-story-grid">${shot('planning','01 / Commit a plan','The staff reservation competes with C-07. Supplier cost buys time but creates a release dependency.')}${shot('paid-record','02 / Save the label','Tuesday v2 records Paid. It becomes an earlier document when the bank returns funding on Wednesday.')}${shot('return','03 / Respond to the return','A trace can unlock approval. A substitute changes production while leaving O-19 open.')}${shot('outcome','04 / Keep both promises visible','The reissue run delivers Friday. A revised promise is kept; the original Thursday promise is not.')}</div><div class="episode-downloads">${gif('supplier-run','Watch supplier route')}${gif('five-views','Compare five views')}${gif('map-cycle','Workshop cycle')}</div>`,`Browser captures of actual fictional play. The controls generated these state changes; this is not a storyboard of unimplemented screens.`),
'episode-clocks':plate('E04','The record does not follow the bank',`<a class="episode-diagram" href="previews/episode/three-clocks.svg" target="_blank"><img src="previews/episode/three-clocks.svg" alt="Separate work, bank and saved-record timelines show a new P-05 without rewriting Tuesday v2" loading="lazy"></a>`,`The player-created reissue belongs to the simulation. The fixed fixture and historical source retain their own limits. <a href="previews/episode/three-clocks.svg" download>SVG ↓</a> · <a href="previews/episode/three-clocks.gif" download>Still GIF ↓</a>`),
'episode-cash':plate('E05','A delivered job can leave an open bill',`<a class="episode-diagram" href="previews/episode/cash-boundaries.svg" target="_blank"><img src="previews/episode/cash-boundaries.svg" alt="Substitute route closes with $26,500 posted cash, $12,000 reserved and $14,500 available; campaign ceiling and receivable remain separate" loading="lazy"></a>`,`Closeout values generated from the substitute route. <a href="previews/episode/substitute-outcome.png">Inspect the actual outcome ↗</a> · <a href="previews/episode/cash-boundaries.svg" download>SVG ↓</a> · <a href="previews/episode/cash-boundaries.gif" download>Still GIF ↓</a>`)
};
