const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const svg=(w,h,body,label)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${e(label)}"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="none" stroke="currentColor" stroke-width="1.5"/></marker><pattern id="hatch" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M0 5L5 0" stroke="#bdbdc4" stroke-width=".7"/></pattern></defs>${body}</svg>`;
const text=(x,y,str,size=14,weight=400,fill='currentColor')=>`<text x="${x}" y="${y}" font-size="${size}" font-weight="${weight}" fill="${fill}">${e(str)}</text>`;
const node=(x,y,w,h,title,sub='',active=false,tint='')=>`<g><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${tint||(active?'#4fea79':'#fff')}" stroke="#28282c" stroke-width="1.2"/>${text(x+15,y+27,title,17,500,active?'#131316':'#131316')}${sub?text(x+15,y+48,sub,12,400,active?'#131316':'#6a6a70'):''}</g>`;
const edge=(points,label,x,y,dash=false)=>`<path d="${points}" fill="none" stroke="currentColor" stroke-width="1.1" marker-end="url(#arrow)" ${dash?'stroke-dasharray="5 4"':''}/>${label?text(x,y,label,12):''}`;
const fig=(id,title,body,caption='')=>`<figure class="plate" id="fig-${id}"><figcaption><span class="figure-id">FIG. ${id}</span><strong>${title}</strong></figcaption><div class="figure-body">${body}</div>${caption?`<div class="figure-note">${caption}</div>`:''}</figure>`;
const figures={};
figures['chapter-lanes']=fig('01','Player agency and the historical record',`<div class="lanes"><div class="lane-label">Practice<span>Invented conditions</span></div><div class="lane"><b>Plan</b><span>→</span><b>Run</b><span>→</span><b>Respond</b><span>→</span><b>Review outcome</b></div><div class="lane-label fixed">History<span>Fixed records</span></div><div class="lane historical"><span class="empty-track"></span><div><b>Compare the mechanism</b><small>What does the source establish?</small></div><a href="#evidence/source-classes">Open supporting records ↗</a></div></div>`,`The player's run changes the practice outcome. The historical comparison retains its own dates, permissions and source limits.`);
figures['first-episode']=fig('02','Prototype sequence',`<ol class="episode-strip">${[
['00–03','Plan production','Choose a plan and work bay. Allocate the shared staff.'],['03–06','Run the plan','Resolve a capacity conflict. Watch a deliverable progress.'],['06–09','Inspect payment','Supplier route only: compare obligation, return and saved Paid label.'],['09–12','Protect delivery','Seek approval to reissue, build a substitute or revise the handoff.'],['12–15','Compare outcomes','Inspect valid pooling, review the run and enter the historical comparison.']
].map(x=>`<li><span class="time">${x[0]} min</span><span class="timeline-mark"></span><h4>${x[1]}</h4><p>${x[2]}</p></li>`).join('')}</ol>`,`Target session pacing, not measured playtest timing. In-house and ordinary runs avoid the payment exception. The final historical comparison is read-only.`);
figures['payment-lifecycle']=fig('03','One obligation; three independent states',`<div class="scroll-figure" tabindex="0" role="region" aria-label="Diagram; scroll horizontally on smaller screens">${svg(900,306,`
${text(198,27,'Agreement',13,500)}${text(379,27,'Attempt',13,500)}${text(559,27,'Return',13,500)}${text(739,27,'Later endpoint',13,500)}
<path d="M180 42H880 M180 126H880 M180 210H880" stroke="#c7c7cd" fill="none"/>
${text(15,82,'Obligation',15,500)}${text(15,166,'Bank events',15,500)}${text(15,250,'Platform',15,500)}
${node(195,56,142,55,'$12,000 USD','Fabrication owed')}${edge('M337 84H537','',0,0)}${node(555,56,317,55,'Still requires resolution','Settlement is not supplied in this fixture')}
${node(375,140,143,55,'− $12,000','Debit')}${edge('M518 168H544','',0,0)}${node(555,140,143,55,'+ $12,000','Equal return')}<rect x="735" y="140" width="137" height="55" fill="url(#hatch)" stroke="currentColor" stroke-dasharray="4 3"/>${text(749,165,'Not supplied',15,500)}${text(749,183,'Later settlement',12)}
${node(195,224,142,55,'Scheduled','Record v1',false,'#f6d4e3')}${edge('M337 252H364','',0,0)}${node(375,224,143,55,'Paid','Record v2',false,'#f6d4e3')}${edge('M518 252H723','Saved copy',549,241)}${node(735,224,137,55,'Paid','Same v2',false,'#f6d4e3')}
`,'The $12,000 obligation remains unresolved after an equal debit and return. The saved Tuesday Paid record predates the Wednesday return; later platform state and settlement are not supplied.')}</div>`,`C-07 / O-19 · Invented USD example. The saved v2 predates the return. Reading it later is not a later status observation; recipient settlement remains unknown.`);
figures['relationships']=fig('04','A project and its relationships',`<div class="scroll-figure" tabindex="0" role="region" aria-label="Diagram; scroll horizontally on smaller screens">${svg(900,437,`
${node(15,20,185,62,'Client','Commissions work')}${node(327,20,235,62,'Contract','Scope, terms, rights')}${node(702,20,183,62,'Agency entity','Party to the contract')}
${edge('M200 50H317','agrees',247,39)}${edge('M702 50H573','agrees',620,39)}${edge('M444 82V141','defines',456,119)}
${node(15,155,185,70,'Employees','Employment + departments')}${node(327,155,235,70,'Project','Work and dependencies',true)}${node(702,155,183,70,'Supplier','Dated engagement')}
${edge('M200 190H317','supplies labor',218,178)}${edge('M702 190H573','supplies work',587,178)}
${node(15,308,185,62,'Site','Capacity, access, lease')}${node(327,308,235,62,'Payment attempt','Route, return, reissue')}${node(702,308,183,62,'Obligation','Debtor, creditor, terms')}
${edge('M108 308V268H368V236','provides capacity',160,257)}${edge('M794 225V296','creates',806,268)}${edge('M562 340H690','attempts to settle',584,326)}
<path d="M15 394H885" stroke="#b6b6be"/>${text(15,421,'Records describe objects and events. Permissions govern actions. Neither is a physical location.',14)}
`,'A contract links a client and legal entity and defines a project. Employees, a site and a supplier support the project. The supplier engagement creates an obligation; payment attempts try to settle it.')}</div>`);
figures['operating-loop']=fig('05','Production and cash run on different clocks',`<div class="clock-diagram"><div class="clock-row"><b>Work</b><div class="flow">Scope <i>→</i> Capacity <i>→</i> Production <i>→</i> Acceptance <i>→</i> Review</div></div><div class="clock-row"><b>Commitments</b><div class="flow commitments"><span>Deposits</span><span>Payroll</span><span>Supplier milestones</span><span>Invoices due</span></div></div><div class="clock-row"><b>Settlement</b><div class="flow settlements"><span>Client receipts</span><span>Outflows</span><span>Returns / reissues</span></div></div></div>`,`Positions indicate separate processes, not a payment schedule. A deposit, payroll or media payment may precede delivery or client collection.`);
const views=[
['Work','Component awaiting release','Production → supplier handoff','2 team-days reserved','Thursday handoff','Dependency','M200 135H375 M565 135H725'],
['Cash','Attempt returned','Bank debit → equal return','$12,000 USD each','Later settlement not supplied','Cash events','M470 65V97 M565 135H725 M725 152H565'],
['Information','Saved platform version','Record v1 → record v2','Platform state: Paid','Tuesday snapshot; Wednesday return','Record lineage','M470 65V97 M470 173V220'],
['Control','Release requires approval','Preparation ≠ approval','Role may prepare','Separate approver may release','Permission','M200 135H375 M470 173V220'],
['People','Internal and external work','Departments + supplier engagement','Production slot held','Accounts handoff due','Work relationship','M200 135H375 M565 135H725']
];
figures['five-views']=fig('06','One selection across five views',`<div class="view-study"><div class="view-constant"><span><b>C-07 / O-19</b> · Fabricated component</span><span>Event: week 3 · Record: v2</span></div><div class="view-tabs" role="group" aria-label="Select a view">${views.map((v,i)=>`<button data-view="${i}" aria-pressed="${i===0}">${v[0]}</button>`).join('')}</div><div class="view-stage"><div class="view-graph" tabindex="0" role="region" aria-label="Relationship view; scroll horizontally on smaller screens">${svg(920,300,`<g class="view-edges" stroke="#131316" stroke-width="2" fill="none"><path id="view-edge" d="${views[0][6]}"/></g><g id="view-node-left">${node(20,99,180,73,'Departments','Creative / production')}</g>${node(375,99,190,73,'O-19','Selected obligation',true)}<g id="view-node-right">${node(725,99,180,73,'Supplier','External engagement')}</g><g id="view-node-top">${node(375,8,190,56,'Production plan','Capacity / schedule')}</g><g id="view-node-bottom">${node(375,222,190,56,'Release','Approval required')}</g>`,'The obligation O-19 stays selected while relationships change with the chosen view.')}</div><div class="view-inspector" aria-live="polite"><span id="view-kind">Work / O-19</span><h4 id="view-title">${views[0][1]}</h4><p id="view-rel">${views[0][2]}</p><dl><dt>Observed in fixture</dt><dd id="view-a">${views[0][3]}</dd><dt>Context</dt><dd id="view-b">${views[0][4]}</dd></dl></div></div></div>`,`Synthetic relationship study. Selection and period stay fixed; each view exposes a different relationship. This is not a running economy.`);
figures['desk-layouts']=fig('07','Three layouts, one return path',`<div class="desk-studies">${[
['Plan','World + inspector',`<rect x="12" y="33" width="164" height="116" fill="url(#hatch)"/><path d="M12 90H176 M68 33V149 M121 33V149" stroke="#c8c8ce"/><rect x="65" y="63" width="61" height="40" fill="#fff" stroke="#131316" stroke-width="2"/><rect x="183" y="33" width="65" height="116" fill="#fff" stroke="currentColor"/><path d="M191 51H240 M191 63H232 M191 90H240 M191 102H226" stroke="currentColor"/>`],
['Compare','Two records + context',`<rect x="12" y="33" width="113" height="116" fill="#fff" stroke="currentColor"/><rect x="135" y="33" width="113" height="116" fill="#fff" stroke="currentColor"/><path d="M22 51H111 M22 64H103 M145 51H235 M145 64H227 M22 100H109 M145 100H232" stroke="currentColor"/><rect x="21" y="75" width="95" height="11" fill="#131316" opacity=".15"/><rect x="144" y="75" width="95" height="11" fill="url(#hatch)" stroke="currentColor" stroke-dasharray="2 2"/>`],
['Read','Document + source context',`<rect x="12" y="33" width="169" height="116" fill="#fff" stroke="currentColor"/><path d="M25 52H125 M25 71H165 M25 82H162 M25 93H163 M25 112H164 M25 123H151" stroke="currentColor"/><path d="M195 45H242 M195 57H230 M195 85H243 M195 97H231" stroke="currentColor"/>`]
].map((x,i)=>`<div><h4>${x[0]}</h4>${svg(260,177,`<rect x="1" y="1" width="258" height="175" fill="#fff" stroke="currentColor"/><rect x="1" y="1" width="258" height="22" fill="#131316"/>${text(11,16,'C-07 / O-19',10,500,'#fff')}${x[2]}${text(12,167,'← Return to selected project',10)}`,x[1])}<p>${x[1]}</p></div>`).join('')}</div>`);
figures['architecture']=fig('10','Data and presentation boundaries',`<div class="architecture"><div class="architecture-top"><div><b>Source archive + claims</b><span>Inputs, locators, corrections, review states</span></div><div><b>Historical objects + events</b><span>Identities, versions, relationships, uncertainty</span></div><div class="fiction-boundary"><b>Scenario model</b><span>Invented parameters, actions, seeded events</span></div></div><div class="architecture-bottom"><div><b>Presentation</b><span>World · views · records · accessible lists</span></div><div><b>Review tools</b><span>Coverage · change impact · source-to-scene links</span></div></div></div>`,`The scenario has its own state. It cannot overwrite source records or the historical model.`);
// Phase content is parsed from the GDD, rather than maintained a second time here.
function productionPlan(phases){
 const card=p=>`<article class="phase-card ${p.id==='P2'?'phase-next':p.id==='P1'?'phase-parallel':''}" id="production/phase-${p.id.toLowerCase()}" data-phase="${p.id}" data-status="${e(p.status)}"><div class="phase-label"><span>${p.id}</span><b>${e(p.status)}</b></div><h4>${e(p.title)}</h4><p>${e(p.output)}</p><div class="phase-gate"><span>Gate</span>${e(p.gate)}</div></article>`;
 return fig('11','Production sequence',`<div class="phase-complete">${card(phases[0])}</div><div class="production-tracks">${phases.slice(1,3).map(card).join('')}</div><p class="phase-convergence">Validation: P2 → P3 → P4. The fictional P4 loop is built early; P1 still gates historical interaction.</p><div class="phase-queue">${phases.slice(3).map(card).join('')}</div>`,`Phase IDs, status and gates come from the GDD’s production table. <a href="#production/current-focus">Open the current test →</a>`);
}
figures['ordinary-work-proof']=fig('12','One job, two plans',`<div class="work-proof"><div class="work-proof-job"><b>C-07 · Fabricated component</b><span>Same deliverable · same due date · one shared capacity conflict</span></div><div class="work-proof-options"><div><span class="work-proof-option">PLAN A</span><h4>Make in-house</h4><ol><li>Reserve team capacity</li><li>Fabricate the component</li><li>Hand off for delivery</li></ol><p>Staff time and the competing reservation change the result.</p></div><div><span class="work-proof-option">PLAN B</span><h4>Commission S-08</h4><ol><li>Commit $12,000 · O-19</li><li>Confirm supplier receipt</li><li>Hand off for delivery</li></ol><p>External cost and lead time change the result.</p></div></div><div class="work-proof-result"><b>Compare the run</b><span>Delivery time</span><span>Capacity left</span><span>Cash committed</span></div></div>`,`Implemented P2 test. Select the ordinary scenario in Episode 01. Starting cash, costs and timing are specified in the episode rules; participant comprehension remains untested.`);
const viewNodes=[
[['Departments','Creative / production'],['Supplier','External engagement'],['Production plan','Capacity / schedule'],['Release','Approval required']],
[['Bank event','Debit: $12,000 USD'],['Bank event','Return: $12,000 USD'],['Later endpoint','Not supplied'],['Payment attempt','P-04 / returned']],
[['Earlier record','v1 / Scheduled'],['Later record','v2 / Paid'],['Provenance','Synthetic fixture'],['Saved copy','Not a later observation']],
[['Preparer','Can prepare'],['Approver','May release'],['Grant dates','Week 3'],['Platform','Payment tool']],
[['Production','Reserved slot'],['Supplier','External engagement'],['Accounts','Client handoff due'],['Employment','Persistent staff']]
];
views.forEach((v,i)=>v.push(viewNodes[i]));
figures['source-comparison']=`<div class="source-comparison">${[['34','Creative Peaks','Payment state and bank route'],['45','Legitimate pooling controls','Worked chains · continues on p.46']].map(x=>`<a href="../The_Zero_Machine_Specific_Story_Reconstruction%20FINAL.pdf#page=${x[0]}" target="_blank" class="source-excerpt"><span class="excerpt-page"><img src="assets/zero-machine-page-${x[0]}.png" alt="Actual page ${x[0]} of The Zero Machine" loading="lazy"></span><span class="excerpt-caption"><small>CASE-01 / PAGE ${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span><b>Open source page ↗</b></span></a>`).join('')}</div>`;
export {figures,views,productionPlan};
