import { objectMedia, playbackButton } from './object-media.mjs';
const discoveries=[
 {id:'L-05',kind:'voila',title:'Bakery delivery',site:'Porter',file:'voila-facade.png',seen:'Voila Bakeries signage; supplied context identifies the former croissant factory at 65 Porter.',change:'A boxy delivery van with a croissant emblem stops to load, then follows a 32-second service loop.',credit:'Supplied facade and branding reference'},
 {id:'L-07',kind:'reception',title:'Arrival desk',site:'Porter',file:'porter-reception.jpg',seen:'Sculpted white counter, dark flecks and planted recesses.',change:'An open-air park reception replaces the generic ticket hut.',credit:'Matt Fry portfolio · photo credit not established'},
 {id:'L-01',kind:'car',title:'Chrysler circuit',site:'Johnson',file:'johnson-mezzanine.jpg',seen:'A full-sized white Chrysler occupies the office floor.',change:'Park it as a display or run an invented miniature circuit.',credit:'Matt Fry portfolio · photo credit not established'},
 {id:'L-08',kind:'inflatable',title:'Temporary fairground',site:'Johnson',file:'johnson-inflatable.jpg',seen:'An inflatable castle, shark balloon and bunting in the hall.',change:'Swap the courtyard’s booths for an event layout.',credit:'Matt Fry portfolio · photo credit not established'},
 {id:'L-02',kind:'stag',title:'Antler display',site:'Porter',file:'porter-hall.jpg',seen:'Black stag sculpture with reflective antlers among the desks.',change:'Enlarge its silhouette into a small park landmark.',credit:'Photography: Zach Pontz'},
 {id:'L-03',kind:'supernova',title:'Supernova pavilion',site:'Porter',file:'porter-supernova.jpg',seen:'SUPERNOVA names a glazed room with amber curtains.',change:'The name becomes a black-and-silver roadside pavilion with a chrome canopy and orbital sign.',credit:'Photography: Zach Pontz'},
 {id:'L-06',kind:'cat',title:'Office cat',site:'Johnson',file:'johnson-cat.jpg',seen:'Tabby, purple collar, a patch of sunlight by the stair.',change:'A resting tabby beside the workshop, with an animated tail.',credit:'Matt Fry portfolio · photo credit not established'}
];
export const parkFigures={
 'park-discoveries':`<figure class="plate art-plate" id="fig-A11"><figcaption><span class="figure-id">A11</span><strong>Office discoveries</strong></figcaption><div class="kit-tools"><span>Office photograph → park component</span>${playbackButton}</div><div class="park-discoveries">${discoveries.map(d=>`<div class="park-discovery" data-object="${d.id}"><a href="assets/office-references/${d.file}" target="_blank" aria-label="Open ${d.site} photograph for ${d.title}"><img src="assets/office-references/${d.file}" alt="${d.seen}" loading="lazy"></a><div class="park-discovery-content"><small>${d.site.toUpperCase()}</small><h3>${d.title}</h3><p><b>Photograph</b> · ${d.seen}</p><p><b>Park study</b> · ${d.change}</p><small>${d.credit}</small></div><a class="park-discovery-sprite" style="position:relative" href="assets/sprite-catalogue/index.html#${d.id}" aria-label="Inspect ${d.title}">${objectMedia(d.id,{width:240,height:145})}<span class="discovery-object-link">${d.id} · Inspect object ↗</span></a></div>`).join('')}</div><div class="park-discovery-note">Photographs establish the source objects. Scale, placement and motion are designed for the park. The car circuit and Supernova pavilion are inventions. The inflatable is a photographed event object, not evidence of a permanent attraction.</div><div class="figure-note"><a href="#art/world-and-interface">Try the assembled park →</a> · <a href="#research-discoveries">Office sources →</a></div></figure>`
};
