import { objectMedia, playbackButton } from './object-media.mjs';
const sprite=(id,label,w=220,h=150,variant=null)=>`<a class="reading-sprite" href="assets/sprite-catalogue/index.html#${id}" aria-label="${label}: object details">${objectMedia(id,{title:label,width:w,height:h,variant})}</a>`;
const aside=(body,caption,extra='')=>`<figure class="reading-aside ${extra}">${body}<figcaption>${caption}</figcaption></figure>`;
const scene=(kind,label)=>`<div class="reading-scene"><canvas width="320" height="184" data-reading-scene="${kind}" role="img" aria-label="${label}"></canvas><button type="button" data-reading-motion aria-pressed="true" aria-label="Pause illustration">Pause</button></div>`;
export const readingFigures={
 'margin-role':aside(`<div class="reading-crew">${sprite('A-02','Creative worker',60,100)}${sprite('A-05','Production worker',60,100)}${sprite('A-06','Worker carrying a component',60,100)}</div>`,`Fictional staff share the work pool. ${playbackButton}`),
 'margin-site':aside(sprite('B-02','Porter interior',240,140,'roof-off'),'Porter cutaway. A site can house several departments.'),
 'margin-handoff':aside(scene('handoff','A worker carries a component from a workshop towards a delivery van'),'Physical handoff. Near-dock placement saves one interval in Episode 01. <a href="previews/reading/handoff.gif" download>GIF ↓</a>','reading-aside-wide'),
 'margin-people':aside(`<div class="reading-crew">${sprite('A-06','Fictional courier',80,110)}${sprite('A-03','Fictional staff member',80,110)}</div>`,`Role labels identify responsibilities. Shirt colour alone does not. ${playbackButton}`),
 'margin-materials':aside(`<div class="reading-paper-set" aria-label="Invoice, saved platform record and bank extract"><span>INVOICE<small>O-19 · $12,000</small></span><span>SAVED RECORD<small>v2 · Tuesday</small></span><span>BANK EVENTS<small>P-04 · Tue / Wed</small></span></div>`,'Three document types; one obligation. <a href="#art/interface-materials">Open specimens →</a>'),
 'margin-quantity':aside(`<div class="reading-measure"><small>C-07 / FICTIONAL RUN</small><b>$100,000 <em>USD</em></b><dl><dt>Measure</dt><dd>Budget ceiling</dd><dt>Scope</dt><dd>Campaign C-07</dd><dt>Period</dt><dd>Current run</dd><dt>Basis</dt><dd>Scenario terms</dd></dl></div>`,'Keep the measure and basis beside the amount.'),
 'margin-walk':aside(sprite('A-01','Six-leg fedora walk',210,125),`Walk → walk → moonwalk, then repeat in the opposite direction. ${playbackButton}`),
 'margin-components':aside(`<div class="reading-crew">${sprite('M-01','White worktable',105,115)}${sprite('PR-05','Shipping crate',80,90)}</div>`,'Reusable workshop objects. <a href="#art/component-kit">Component kit →</a>'),
 'margin-source':aside(`<a class="reading-source" href="../The_Zero_Machine_Specific_Story_Reconstruction%20FINAL.pdf#page=34"><img src="assets/zero-machine-page-34.png" alt="The Zero Machine page 34" loading="lazy"></a>`,'CASE-01, p.34. Inspect the claim beside its underlying records.'),
 'story-work':aside(scene('workshop','Johnson-derived workshop with an exposed interior and a worker carrying a component'),'Production illustration. <a href="episode-01/index.html">Play C-07 →</a> · <a href="previews/reading/workshop.gif" download>GIF ↓</a>','reading-aside-wide'),
 'story-record':aside(`<div class="reading-carbon"><span>SAVED PLATFORM RECORD</span><h4>Paid</h4><dl><dt>Version</dt><dd>v2</dd><dt>Saved</dt><dd>Tuesday 10:02</dd><dt>Attempt</dt><dd>P-04</dd></dl><b>Reopened Wednesday</b><p>The saved date stays Tuesday.</p></div>`,'Fictional record. <a href="#art/interface-materials">Compare versions →</a>'),
 'story-obligation':aside(`<div class="reading-closeout"><span>SUBSTITUTE ROUTE</span><div><small>C-07 / PRODUCTION</small><b>Delivered</b></div><div><small>O-19 / OBLIGATION</small><b>$12,000 <em>open</em></b></div></div>`,'Completing the job leaves the supplier obligation unresolved.'),
};
function rows(html){return [...html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map(m=>[...m[1].matchAll(/<td>([\s\S]*?)<\/td>/g)].map(t=>t[1].trim())).filter(r=>r.length);}
export function readingLayout(html,kind){
 const cells=rows(html);
 if(kind==='campaign')return `<ol class="campaign-reading">${cells.map(([name,action,distinction,source,requirement],i)=>`<li><div class="campaign-number">${String(i+1).padStart(2,'0')}</div><div class="campaign-content"><h4>${name.replace(/^\d+\. /,'')}</h4><p>${action}.</p><div class="campaign-distinction">${distinction}</div><footer><span>CASE-01 ${source}</span><span><b>Source needed</b> ${requirement}.</span></footer></div><div class="campaign-mark">${i===0?sprite('M-01','Production worktable',125,85):i===4?sprite('B-02','A site and its occupants',125,85):`<canvas width="16" height="16" data-art-icon="${['Work','Control','Information','Cash','Control','Information','Control'][i]}" aria-hidden="true"></canvas>`}</div></li>`).join('')}</ol>`;
 if(kind==='events')return `<div class="event-reading">${cells.map(([name,action,purpose],i)=>`<article><span class="event-index">${String(i+1).padStart(2,'0')}</span><div><h4>${name}</h4><p>${action}.</p><small>${purpose}.</small></div>${[1,3,7].includes(i)?`<span class="event-mark"><canvas width="16" height="16" data-art-icon="${i===1?'Work':i===3?'Cash':'Control'}" aria-hidden="true"></canvas></span>`:''}</article>`).join('')}</div>`;
 return html;
}
