/* Canvas layout and shared-room UI. Episode and workshop rules live in model.js. */
(()=>{'use strict';
const M=window.MMTBoardModel,S=window.MMTBoardStore,A=window.MMTBoardAssets,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+crypto.randomUUID(),W=220,NS='http://www.w3.org/2000/svg';
let board=S.load()||M.seedBoard(),evaluation,selected=null,selectedEdge=null,tool='select',from=null,view='systems',drag=null,space=false,history=[],future=[],timer=null,saveTimer=null,saveBusy=false,saveAgain=false,changedStats=[],category='all',client=null,room=null,roomConflicts=null,localBeforeRoom=null,peers=[],traceFocus=[];
let vp=board.viewport||{x:30,y:30,zoom:.7},lastSaved=clone(board),lastEval=null;
const nodeEl=new Map(),viewport=$('#viewport'),world=$('#world');
function toast(text){$('#board-status').textContent=text;clearTimeout(toast.t);toast.t=setTimeout(()=>$('#board-status').textContent='',4500);}
function pause(){clearInterval(timer);timer=null;$('#run').textContent='Run';}
function remember(){history.push(clone(board));if(history.length>60)history.shift();future=[];}
function changed({evaluate=true}={}){if(client&&room){client.setDraft(snapshotBoard());try{localStorage.setItem('mmt-whiteboard-recovery',S.exportJSON(snapshotBoard()));}catch{}}if(evaluate)render();else renderEdges();scheduleSave();$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;}
function transact(fn){remember();fn();changed();}
function snapshotBoard(){const b=clone(board);b.viewport=clone(vp);return b;}
function saveLabel(text,bad=false){$('#save-state').textContent=text;$('#save-state').classList.toggle('save-error',bad);}
function scheduleSave(){saveLabel(room?'Saving to room…':'Saving locally…');clearTimeout(saveTimer);saveTimer=setTimeout(save,450);}
async function save(){if(saveBusy){saveAgain=true;return;}if(roomConflicts){saveLabel('Conflict · review changes',true);return;}saveBusy=true;try{const snapshot=snapshotBoard();if(client&&room){const result=await client.sync(snapshot);if(result.ok){lastSaved=clone(snapshot);saveLabel('Shared · saved');}else if(result.conflicts?.length){roomConflicts=result;showConflict();}else saveLabel(result.message||'Shared save failed · export a backup',true);}else{const result=await S.saveLocked(snapshot);if(result.ok){lastSaved=clone(snapshot);saveLabel('Saved locally');$('#conflict-banner').hidden=true;}else{saveLabel(result.message||'Save failed',true);if(result.conflict)$('#conflict-banner').hidden=false;}}}catch(e){saveLabel('Save failed · export a backup',true);toast(e.message);}finally{saveBusy=false;if(saveAgain){saveAgain=false;scheduleSave();}}}
function getNode(id){return board.nodes.find(n=>n.id===id);}
function visibility(n){if(view==='systems')return !['story','structure'].includes(n.params?.mode);if(view==='story')return n.type==='beat';return n.type!=='zone'&&n.type!=='note'&&n.type!=='beat';}
function position(n){const custom=n.params?.positions?.[view];if(custom)return custom;if(view==='systems')return{x:n.x,y:n.y};if(view==='story'){const ordered=board.nodes.filter(n=>n.type==='beat').sort((a,b)=>(a.params?.order||0)-(b.params?.order||0));return{x:80+ordered.indexOf(n)*285,y:130};}const visible=board.nodes.filter(visibility),anchors=visible.filter(n=>n.type==='anchor'),parent=n.params?.parentId;if(n.type==='anchor'){if(!parent)return{x:Math.max(40,(anchors.length-2)*310/2+40),y:50};return{x:40+Math.max(0,anchors.filter(a=>a.params?.parentId).indexOf(n))*310,y:200};}const pIndex=anchors.filter(a=>a.params?.parentId).findIndex(a=>a.id===parent);const siblings=visible.filter(a=>a.type!=='anchor'&&(a.params?.parentId||'')===(parent||''));return{x:40+(pIndex<0?anchors.filter(a=>a.params?.parentId).length:pIndex)*310,y:350+Math.max(0,siblings.indexOf(n))*100};}
function setPosition(n,p){if(view==='systems'){n.x=p.x;n.y=p.y;}else{n.params.positions=n.params.positions||{};n.params.positions[view]=p;}}
function art(id,width=190,height=96){const a=A.find(x=>x.id===id);if(!a)return'';const d=a.display,b=d.bounds,fit=Math.min(4,width/b.width,height/b.height),k=fit>=1?Math.floor(fit):fit;return `<span class="sprite-box" style="height:${height}px"><img alt="${esc(a.name)}" src="../assets/sprite-catalogue/${d.poster}" ${d.animated?`data-motion-src="../assets/sprite-catalogue/${d.gif}"`:''} style="width:${d.width*k}px;height:${d.height*k}px;left:calc(50% - ${(b.x+b.width/2)*k}px);top:calc(50% - ${(b.y+b.height/2)*k}px)"></span>`;}
const artFor=n=>n.params?.assetId||({'staff':'A-05','project':'PR-05','supplier':'PR-04','site':'B-03','archetype':'A-03'}[n.type]);
function nodeBody(n,s){if(n.type==='zone')return `<div class="zone-slot">Drop work bay here</div>`;if(n.type==='beat'){const refs=(n.params.references||[]).map(id=>getNode(id)).filter(Boolean);return `<p class="node-detail">${esc(n.params.note)}</p><div class="beat-objects">${refs.slice(0,3).map(r=>`<button data-reveal="${esc(r.id)}" title="Inspect ${esc(r.title)}">${artFor(r)?art(artFor(r),70,50):'<span class="paper-mini">'+esc(r.type)+'</span>'}<span>${esc(r.title)}</span></button>`).join('')}</div><span class="node-status">${esc(s.state)} · ${refs.length} linked objects</span>`;}if(n.type==='anchor')return `<p class="node-detail">${esc(n.params.note)}</p><span class="node-status">${board.nodes.filter(x=>x.params?.parentId===n.id).length} children</span>`;
const id=artFor(n),doc=['record','payment','obligation','approval'].includes(n.type);return `${id?`<div class="node-art">${art(id)}</div>`:doc?`<div class="record-strip"><span>${esc((n.ref||n.type).replace('episode:',''))}</span><span>${n.type==='record'?'SAVED COPY':n.type==='payment'?'ATTEMPT':n.type==='obligation'?'INVOICE':'CONTROL'}</span></div>`:''}<p class="node-detail">${esc(s.detail||n.params?.note||'')}</p>${n.type==='effect'?`<div class="effect-equation">${esc(n.params.metric||'work')} ${n.params.operation==='set'?'=':'+='} ${esc(n.params.value)}</div>`:''}<span class="node-status">${esc(s.state||'proposal')}</span>`;}
function renderNodes(){const visible=board.nodes.filter(visibility),ids=new Set(visible.map(n=>n.id));for(const [id,el]of nodeEl)if(!ids.has(id)){el.remove();nodeEl.delete(id);}for(const n of visible){let el=nodeEl.get(n.id);if(!el){el=document.createElement('article');el.tabIndex=0;el.dataset.node=n.id;el.className='board-node';$('#nodes').append(el);nodeEl.set(n.id,el);}const s=evaluation.nodes[n.id]||{},p=position(n);el.style.left=p.x+'px';el.style.top=p.y+'px';el.className=`board-node type-${n.type} ${s.scope==='proposal'?'proposal':''} ${n.id===selected?'selected':''} ${['held','blocked','late'].includes(s.state)?'blocked':''} ${['fired','ready','complete'].includes(s.state)?'active':''} ${traceFocus.includes(n.id)?'trace-focus':''}`;el.setAttribute('aria-label',n.title+', '+(s.detail||n.type));const html=`<div class="node-head"><span class="node-kind">${esc(n.type==='beat'?'BEAT '+String(n.params.order||0).padStart(2,'0'):n.type)}</span><b class="node-title">${esc(n.title)}</b>${n.type!=='zone'?`<button class="node-port" data-port="${esc(n.id)}" title="Connect from ${esc(n.title)}" aria-label="Connect from ${esc(n.title)}">↗</button>`:''}</div><div class="node-body">${nodeBody(n,s)}</div>`;if(el._html!==html){el.innerHTML=html;el._html=html;}}
renderEdges();}
function shownEdges(){if(view==='structure')return board.nodes.filter(visibility).filter(n=>getNode(n.params?.parentId)).map(n=>({id:'hierarchy:'+n.id,from:n.params.parentId,to:n.id,kind:'contains',label:''}));return board.edges.filter(e=>visibility(getNode(e.from)||{})&&visibility(getNode(e.to)||{})).map(e=>view==='story'?{...e,label:''}:e);}
function renderEdges(){const paths=[];for(const e of shownEdges()){const a=nodeEl.get(e.from),b=nodeEl.get(e.to);if(!a||!b)continue;const p=position(getNode(e.from)),q=position(getNode(e.to)),st=evaluation?.edges[e.id]||{},vertical=view==='structure'||Math.abs(q.y-p.y)>Math.abs(q.x-p.x);let x1,y1,x2,y2,d;if(view==='structure'){x1=p.x+a.offsetWidth/2;y1=p.y+a.offsetHeight;x2=q.x;y2=q.y+b.offsetHeight/2;const bus=q.x-24;d=`M${x1} ${y1} L${x1} ${y1+20} L${bus} ${y1+20} L${bus} ${y2} L${x2} ${y2}`;}else if(vertical){x1=p.x+a.offsetWidth/2;y1=p.y+(q.y>p.y?a.offsetHeight:0);x2=q.x+b.offsetWidth/2;y2=q.y+(q.y>p.y?0:b.offsetHeight);const mid=(y1+y2)/2;d=`M${x1} ${y1} C${x1} ${mid} ${x2} ${mid} ${x2} ${y2}`;}else{x1=p.x+(q.x>p.x?a.offsetWidth:0);y1=p.y+a.offsetHeight/2;x2=q.x+(q.x>p.x?0:b.offsetWidth);y2=q.y+b.offsetHeight/2;const k=Math.max(65,Math.abs(x2-x1)*.5)*(q.x>p.x?1:-1);d=`M${x1} ${y1} C${x1+k} ${y1} ${x2-k} ${y2} ${x2} ${y2}`;}const color=e.id===selectedEdge?'#121416':st.blocked?'#bc3f36':st.active?'#168244':e.kind==='requires'?'#9c5977':'#909798';paths.push(`<g class="connection ${st.active?'active':''}" data-edge="${esc(e.id)}"><path class="connection-hit" d="${d}"/><path d="${d}" fill="none" stroke="${color}" stroke-width="${e.id===selectedEdge?3:1.7}" ${e.kind==='informs'?'stroke-dasharray="5 5"':''} marker-end="url(#edge-arrow)"/>${e.label?`<text x="${(x1+x2)/2}" y="${(y1+y2)/2-9}" text-anchor="middle">${esc(e.label)}</text>`:''}</g>`);}
$('#connections').innerHTML='<defs><marker id="edge-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#747b7a"/></marker></defs>'+paths.join('');}
function renderInk(){const strokes=board.ink||[];$('#ink-layer').innerHTML=strokes.filter(s=>!s.view||s.view===view).map(s=>`<path d="${s.points.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}" fill="none" stroke="${esc(s.color)}" stroke-width="${s.width}" stroke-linejoin="round" stroke-linecap="round"/>`).join('');}
function transform(){world.style.transform=`translate(${vp.x}px,${vp.y}px) scale(${vp.zoom})`;$('#zoom-label').textContent='Fit · '+Math.round(vp.zoom*100)+'%';viewport.style.backgroundSize=`${20*vp.zoom}px ${20*vp.zoom}px`;viewport.style.backgroundPosition=`${vp.x}px ${vp.y}px`;}
function bounds(){const visible=board.nodes.filter(visibility);return visible.reduce((r,n)=>{const p=position(n),e=nodeEl.get(n.id);return {x:Math.min(r.x,p.x),y:Math.min(r.y,p.y),r:Math.max(r.r,p.x+(e?.offsetWidth||W)),b:Math.max(r.b,p.y+(e?.offsetHeight||220))};},{x:Infinity,y:Infinity,r:-Infinity,b:-Infinity});}
function fit(){const b=bounds();if(!Number.isFinite(b.x))return;const w=viewport.clientWidth,h=viewport.clientHeight;vp.zoom=Math.max(.2,Math.min(1.05,(w-90)/(b.r-b.x),(h-210)/(b.b-b.y)));vp.x=(w-(b.r-b.x)*vp.zoom)/2-b.x*vp.zoom;vp.y=115+(h-210-(b.b-b.y)*vp.zoom)/2-b.y*vp.zoom;transform();}
function renderStats(){const prev=lastEval;changedStats=evaluation.stats.filter(s=>prev?.stats.find(a=>a.key===s.key)?.raw!==s.raw&&prev?.stats.some(a=>a.key===s.key)).map(s=>({label:s.label,from:prev.stats.find(a=>a.key===s.key).value,to:s.value,nodeIds:[]}));$('#stats').innerHTML=evaluation.stats.map(s=>`<div class="stat ${s.scope==='proposal'?'proposal-stat':''}"><span>${esc(s.label)}</span><strong>${esc(s.value)}</strong>${s.delta?`<small>${s.delta>0?'+':''}${s.unit==='USD'?MMTEpisode.money(s.delta):s.delta} vs defaults</small>`:''}</div>`).join('');lastEval=evaluation;}
function render(){try{evaluation=M.evaluate(board);}catch(e){toast('Cannot evaluate: '+e.message);return;}renderNodes();renderInk();renderStats();if(document.activeElement!==$('#board-title'))$('#board-title').value=board.title;$('#scenario-mode').value=board.scenario.mode;$('#scenario-plan').value=board.scenario.plan;$('#scenario-crew').value=board.scenario.crew;$('#clock').textContent=evaluation.currentTime;$('#signal-count').textContent=evaluation.signals.length;$('#step').disabled=!evaluation.availableActions.some(a=>a.id==='advance');$('#run').disabled=$('#step').disabled;if($('#step').disabled)pause();renderInspector();renderTrace();window.MMTPreviewMotion?.refresh();requestAnimationFrame(renderEdges);}
function field(label,name,value,{type='text',options,max,min,step}={}){const content=options?`<select data-field="${name}">${options.map(o=>`<option value="${esc(typeof o==='string'?o:o[0])}" ${(typeof o==='string'?o:o[0])==value?'selected':''}>${esc(typeof o==='string'?o:o[1])}</option>`).join('')}</select>`:type==='textarea'?`<textarea data-field="${name}" rows="4">${esc(value)}</textarea>`:`<input data-field="${name}" type="${type}" value="${esc(value)}" ${max!=null?`max="${max}"`:''} ${min!=null?`min="${min}"`:''} ${step?`step="${step}"`:''}>`;return `<label class="field"><span>${label}</span>${content}</label>`;}
function actionsHTML(){const actions=evaluation.availableActions.filter(a=>a.id!=='advance'&&!a.id.startsWith('fire:'));return actions.length?`<section class="inspector-section"><h3>Available actions</h3><div class="action-list">${actions.map(a=>`<button data-action="${esc(a.id)}">${esc(a.label)}</button>`).join('')}</div></section>`:'';}
function signalHTML(signals){return signals.map(s=>`<button class="signal ${esc(s.severity)}" data-focus-ids="${esc((s.nodeIds||[]).join('|'))}"><b>${esc(s.title)}</b><span>${esc(s.detail)}</span></button>`).join('');}
function renderInspector(){if($('#inspector').hidden)return;if(document.activeElement?.closest('#inspector-body [data-field]'))return;const n=getNode(selected),edge=board.edges.find(e=>e.id===selectedEdge);let content='';if(edge){$('#inspector-title').textContent='Connection';content=field('Label','edge-label',edge.label)+field('Relationship','edge-kind',edge.kind,{options:[['flow','Flow →'],['requires','Requires'],['informs','Informs']]})+`<p class="scope-label">${esc(evaluation.edges[edge.id]?.detail)}</p><button class="delete-button" id="delete-selection">Remove connection</button>`;}else if(n){$('#inspector-title').textContent=n.type==='beat'?'Story beat':'Card';const s=evaluation.nodes[n.id];content=field('Title','title',n.title);if(n.params?.note!=null||['note','archetype','artifact','beat','anchor'].includes(n.type))content+=field(n.type==='beat'?'What the player learns':'Notes','note',n.params.note||'',{type:'textarea'});if(n.type==='trigger')content+=field('Fires on','event',n.params.event,{options:M.events.map(e=>[e,({manual:'Manual fire',interval:'Each half-day',return:'Funding returns',delivered:'C-07 delivered'}[e])])})+(n.params.event==='manual'?`<button class="primary" data-action="fire:${esc(n.id)}">Fire trigger →</button>`:'');if(n.type==='effect')content+=field('Proposal counter','metric',n.params.metric)+field('Operation','operation',n.params.operation,{options:[['add','Add'],['set','Set']]})+field('Value','value',n.params.value,{type:'number',min:-100000,max:100000,step:'any'});if(n.type==='site'&&n.ref==='episode:work-bay')content+=field('Placement','placement',board.scenario.placement,{options:[['near','Near dock · 1 interval'],['shared','Shared floor · 2 intervals']]});if(n.type==='beat')content+=field('Order','order',n.params.order||1,{type:'number',min:0,max:999,step:1})+field('Reveal state follows','condition',n.params.condition||'',{options:[['','No run condition'],['brief','Brief'],['production','Production starts'],['saved-paid','Saved Paid record'],['funding-return','Funding return'],['recovery','Response chosen'],['delivery','Delivery']]})+`<fieldset class="reference-picker"><legend>Objects in this beat</legend>${board.nodes.filter(r=>!['beat','anchor','zone'].includes(r.type)).map(r=>`<label><input type="checkbox" data-reference="${esc(r.id)}" ${(n.params.references||[]).includes(r.id)?'checked':''}>${esc(r.title)}</label>`).join('')}</fieldset>`;if(n.type!=='zone')content+=field('Parent anchor','parentId',n.params.parentId||'',{options:[['','No parent'],...board.nodes.filter(a=>a.type==='anchor'&&a.id!==n.id).map(a=>[a.id,a.title])]});content+=`<div class="scope-label"><b>${s.scope==='episode'?'Episode rule':s.scope==='layout'?'Placement zone':'Workshop proposal'}</b><p>${esc(s.detail)}</p>${n.ref?`<code>${esc(n.ref)}</code>`:''}</div>`;
if(['obligation','supplier','payment','staff','project'].includes(n.type))content+=`<details open><summary>Workshop assumptions · USD</summary>${Object.entries(M.assumptions).map(([key,spec])=>field(spec.label,'assumption:'+key,board.scenario.assumptions?.[key]??spec.default,{type:'number',min:0,max:10000000,step:'.01'})).join('')}</details>`;const relevant=evaluation.signals.filter(s=>s.nodeIds?.includes(n.id));content+=signalHTML(relevant)+actionsHTML()+`<div class="selection-actions"><button id="duplicate-selection">Duplicate</button><button id="delete-selection">Remove card</button></div>`;}else{$('#inspector-title').textContent='Run';content=actionsHTML()+signalHTML(evaluation.signals);}
if(changedStats.length)content+=`<section class="inspector-section"><h3>Last change</h3><div class="impact-list">${changedStats.map(d=>`<p>${esc(d.label)}<br><s>${esc(d.from)}</s> → <b>${esc(d.to)}</b></p>`).join('')}</div></section>`;
$('#inspector-body').innerHTML=content;}
function renderTrace(){$('#trace-body').innerHTML=`${changedStats.length?`<div class="trace-changes">${changedStats.map(d=>`<p>${esc(d.label)}: ${esc(d.from)} → ${esc(d.to)}</p>`).join('')}</div>`:''}${signalHTML(evaluation.signals)}${actionsHTML()}<ol class="trace-list">${evaluation.trace.length?evaluation.trace.map(t=>`<li><button data-focus-ids="${esc(t.nodeId||'')}"><small>${esc(t.time||'Step '+t.turn)} · ${esc(t.scope)}</small><span>${esc(t.text)}</span></button></li>`).join(''):'<li>Step the episode or fire a manual trigger to start a trace.</li>'}</ol>`;}
function select(id,edge=null){selected=id;selectedEdge=edge;traceFocus=[];$('#inspector').hidden=false;document.body.classList.add('inspector-open');renderNodes();renderInspector();if(id&&vp.zoom<.7){const n=getNode(id),p=position(n);vp.zoom=.85;vp.x=viewport.clientWidth/2-(p.x+110)*vp.zoom;vp.y=viewport.clientHeight/2-(p.y+110)*vp.zoom;transform();}}
function closeInspector(){selected=null;selectedEdge=null;$('#inspector').hidden=true;document.body.classList.remove('inspector-open');renderNodes();}
function setTool(value){tool=value;from=null;$$('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tool===tool));viewport.dataset.tool=tool;$('#canvas-hint').textContent=tool==='connect'?'Choose a source card, then a target · Esc cancels':tool==='pen'?'Draw on the board · V returns to select':'Drag to arrange · scroll to zoom · space to pan';}
function connect(id){if(!from){from=id;toast('Choose the target card');return;}if(from===id){from=null;toast('Connection cancelled');return;}const source=from;transact(()=>board.edges.push({id:uid('edge'),from:source,to:id,kind:'flow',label:'Flow'}));from=null;select(null,board.edges.at(-1).id);toast(evaluation.edges[board.edges.at(-1).id].detail);}
function coords(e){const r=viewport.getBoundingClientRect();return{x:(e.clientX-r.left-vp.x)/vp.zoom,y:(e.clientY-r.top-vp.y)/vp.zoom};}
function center(){return{x:(viewport.clientWidth/2-vp.x)/vp.zoom-W/2,y:(viewport.clientHeight/2-vp.y)/vp.zoom-70};}
function addCard(type,assetId){const def=M.types.find(t=>t.id===type)||M.types.find(t=>t.id==='artifact'),p=center(),a=A.find(a=>a.id===assetId);let n;transact(()=>{n={id:uid(type),type,title:a?.name||def.label,x:p.x,y:p.y,...clone(def.defaults),params:{...clone(def.defaults.params),...(assetId?{assetId}:{}),...(type==='beat'?{mode:'story',order:board.nodes.filter(n=>n.type==='beat').length+1}:{}),...(type==='anchor'?{mode:'structure'}:{})}};if(view!=='systems')n.params.positions={[view]:p};board.nodes.push(n);});document.body.classList.remove('library-open');if(!visibility(n))setView(type==='beat'?'story':type==='anchor'?'structure':'systems');select(n.id);}
function renderLibrary(){const q=$('#library-search').value.toLowerCase();let types=M.types.filter(t=>t.id!=='zone');if(category==='rules')types=types.filter(t=>t.group==='Rules');if(category==='objects')types=[];$('#library-items').innerHTML=types.filter(t=>(t.label+' '+t.description).toLowerCase().includes(q)).map(t=>`<button class="library-item" data-add-type="${t.id}" title="${esc(t.description)}"><span class="library-symbol symbol-${t.id}">${({trigger:'↯',effect:'±',note:'✎',beat:'01',anchor:'⊞',record:'▤',payment:'↗',staff:'♙'}[t.id])||'□'}</span><span class="library-label">${esc(t.label)}<small>${esc(t.group)}</small></span><span aria-hidden="true">＋</span></button>`).join('')+(category!=='rules'?A.filter(a=>(a.name+' '+a.group).toLowerCase().includes(q)&&!a.id.startsWith('U-')&&!a.id.startsWith('G-')&&!a.id.startsWith('S-')).map(a=>`<button class="library-item" data-add-asset="${a.id}"><span class="library-sprite">${art(a.id,44,43)}</span><span class="library-label">${esc(a.name)}<small>${esc(a.id)} · Object</small></span><span aria-hidden="true">＋</span></button>`).join(''):'');}
function setView(next){view=next;client?.presence({view});selected=null;selectedEdge=null;from=null;document.body.dataset.view=view;$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));closeInspector();render();fit();$('#canvas-hint').textContent=({systems:'Flow, gates and resource changes',story:'Ordered beats · select a beat to inspect its objects',structure:'Episode → gameplay anchors → objects and rules'}[view]);}
function act(id){const a=evaluation.availableActions.find(a=>a.id===id);if(!a)return;try{remember();board=M.step(board,a.action);changed();}catch(e){toast(e.message);pause();}}
viewport.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;const port=e.target.closest('[data-port]'),card=e.target.closest('[data-node]'),edge=e.target.closest('[data-edge]');if(port){e.preventDefault();if(tool!=='connect')setTool('connect');connect(port.dataset.port);return;}if(e.target.closest('button,input,select,textarea'))return;if(tool==='connect'&&card){connect(card.dataset.node);return;}if(edge){select(null,edge.dataset.edge);return;}const p=coords(e);if(tool==='pen'&&!space){remember();const stroke={id:uid('ink'),color:'#27282d',width:2,points:[p]};board.ink.push(stroke);drag={kind:'ink',stroke};}else if(card&&!space&&e.button!==1){const n=getNode(card.dataset.node);select(n.id);remember();drag={kind:'node',id:n.id,p,start:position(n),moved:false};}else{drag={kind:'pan',x:e.clientX,y:e.clientY,start:clone(vp)};}viewport.setPointerCapture(e.pointerId);e.preventDefault();});
viewport.addEventListener('pointermove',e=>{const p=coords(e);if(client&&room)client.presence({...p,view});if(!drag)return;if(drag.kind==='pan'){vp.x=drag.start.x+e.clientX-drag.x;vp.y=drag.start.y+e.clientY-drag.y;transform();}else if(drag.kind==='ink'){if(drag.stroke.points.length<4000){drag.stroke.points.push(p);renderInk();}}else{const n=getNode(drag.id);if(!n)return;setPosition(n,{x:Math.round(Math.max(-3000,Math.min(12000,drag.start.x+p.x-drag.p.x))),y:Math.round(Math.max(-3000,Math.min(12000,drag.start.y+p.y-drag.p.y)))});drag.moved=true;const el=nodeEl.get(n.id),now=position(n);el.style.left=now.x+'px';el.style.top=now.y+'px';renderEdges();if(n.ref==='episode:work-bay')for(const zone of board.nodes.filter(n=>n.type==='zone')){const z=position(zone);nodeEl.get(zone.id)?.classList.toggle('drop-target',p.x>=z.x&&p.x<=z.x+255&&p.y>=z.y&&p.y<=z.y+260);}}});
function endDrag(){if(!drag)return;if(drag.kind==='node'){const n=getNode(drag.id);if(n?.ref==='episode:work-bay'&&view==='systems'){const p=position(n),zone=board.nodes.filter(n=>n.type==='zone').find(z=>p.x+110>=z.x&&p.x+110<=z.x+255&&p.y+80>=z.y&&p.y+80<=z.y+260);if(zone&&board.scenario.placement!==zone.params.zone){board.scenario.placement=zone.params.zone;toast('Work bay moved · handoff time recalculated');}}}const was=drag.kind;drag=null;if(was!=='pan')changed();else scheduleSave();}
viewport.addEventListener('pointermove',()=>{if(drag&&client&&room)client.setDraft(snapshotBoard());});
viewport.addEventListener('pointerup',endDrag);viewport.addEventListener('pointercancel',endDrag);
viewport.addEventListener('wheel',e=>{if(e.target.closest('.board-node textarea'))return;e.preventDefault();zoom(Math.exp(-e.deltaY*.0014),e.clientX,e.clientY);},{passive:false});
function zoom(f,cx,cy){const r=viewport.getBoundingClientRect(),x=(cx??r.left+r.width/2)-r.left,y=(cy??r.top+r.height/2)-r.top,old=vp.zoom;vp.zoom=Math.max(.18,Math.min(2.2,vp.zoom*f));vp.x=x-(x-vp.x)*vp.zoom/old;vp.y=y-(y-vp.y)*vp.zoom/old;transform();scheduleSave();}
function removeSelection(){if(!selected&&!selectedEdge)return;transact(()=>{if(selected){board.nodes=board.nodes.filter(n=>n.id!==selected);board.edges=board.edges.filter(e=>e.from!==selected&&e.to!==selected);for(const n of board.nodes){if(n.params?.parentId===selected)delete n.params.parentId;if(n.params?.references)n.params.references=n.params.references.filter(id=>id!==selected);}}else board.edges=board.edges.filter(e=>e.id!==selectedEdge);selected=null;selectedEdge=null;});}
function undo(redo=false){pause();const src=redo?future:history,dst=redo?history:future;if(!src.length)return;dst.push(clone(board));board=src.pop();changed();}
function handleField(e){const key=e.target.dataset.field;if(!key)return;pause();const n=getNode(selected),edge=board.edges.find(x=>x.id===selectedEdge),value=e.target.value;transact(()=>{if(key.startsWith('assumption:')){board.scenario.assumptions=board.scenario.assumptions||{};board.scenario.assumptions[key.split(':')[1]]=Number(value);}else if(key==='placement'){board.scenario.placement=value;const zone=board.nodes.find(n=>n.type==='zone'&&n.params.zone===value);if(zone&&n){n.x=zone.x+16;n.y=zone.y+90;}}else if(edge){if(key==='edge-label')edge.label=value;if(key==='edge-kind')edge.kind=value;}else if(n){if(key==='title')n.title=value;else if(key==='references')n.params.references=value.split(',').map(x=>x.trim()).filter(id=>getNode(id));else if(key==='parentId'){let p=getNode(value),cycle=false;for(let i=0;p&&i<board.nodes.length;i++){if(p.id===n.id){cycle=true;break;}p=getNode(p.params?.parentId);}if(cycle){toast('A card cannot contain its own parent.');return;}n.params.parentId=value;}else n.params[key]=['value','order'].includes(key)?Number(value):value;}});}
$('#inspector-body').addEventListener('change',e=>{if(e.target.dataset.reference){const n=getNode(selected),id=e.target.dataset.reference,on=e.target.checked;transact(()=>n.params.references=on?[...new Set([...(n.params.references||[]),id])]:(n.params.references||[]).filter(x=>x!==id));}else if(e.target.tagName==='SELECT')handleField(e);});
$('#inspector-body').addEventListener('input',e=>{if(e.target.tagName!=='SELECT'&&e.target.validity.valid)handleField(e);});
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.port&&e.detail===0){if(tool!=='connect')setTool('connect');connect(t.dataset.port);}if(t.dataset.tool)setTool(t.dataset.tool);if(t.dataset.category){category=t.dataset.category;$$('[data-category]').forEach(b=>b.setAttribute('aria-pressed',b===t));renderLibrary();}if(t.dataset.addType)addCard(t.dataset.addType);if(t.dataset.addAsset)addCard('artifact',t.dataset.addAsset);if(t.dataset.action)act(t.dataset.action);if(t.dataset.view)setView(t.dataset.view);if(t.dataset.reveal){setView('systems');select(t.dataset.reveal);focusNodes([t.dataset.reveal]);}if(t.hasAttribute('data-focus-ids'))focusNodes(t.dataset.focusIds.split('|').filter(Boolean));if(t.id==='delete-selection')removeSelection();if(t.id==='duplicate-selection'&&getNode(selected)){const n=clone(getNode(selected));transact(()=>{n.id=uid(n.type);n.title+=' copy';n.x+=40;n.y+=40;if(n.params.positions)for(const p of Object.values(n.params.positions)){p.x+=40;p.y+=40;}board.nodes.push(n);});select(n.id);}});
function focusNodes(ids){if(!ids.length)return;traceFocus=ids;const n=getNode(ids[0]);if(!n)return;if(!visibility(n))setView(n.type==='beat'?'story':n.type==='anchor'?'structure':'systems');traceFocus=ids;renderNodes();const p=position(n);vp.zoom=Math.max(vp.zoom,.8);vp.x=viewport.clientWidth/2-(p.x+110)*vp.zoom;vp.y=viewport.clientHeight/2-(p.y+110)*vp.zoom;transform();}
$('#board-title').addEventListener('input',e=>transact(()=>board.title=e.target.value.trim()||'Untitled board'));
for(const key of ['mode','plan','crew'])$('#scenario-'+key).addEventListener('change',e=>{pause();transact(()=>board.scenario[key]=key==='crew'?Number(e.target.value):e.target.value);});
$('#step').onclick=()=>{pause();act('advance');};$('#run').onclick=()=>{if(timer)return pause();act('advance');if($('#step').disabled)return;$('#run').textContent='Pause';timer=setInterval(()=>act('advance'),1400);};$('#reset-run').onclick=()=>{pause();transact(()=>board=M.step(board,{type:'reset'}));};
$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#fit').onclick=fit;$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#close-inspector').onclick=closeInspector;$('#show-trace').onclick=()=>{$('#trace-panel').hidden=!$('#trace-panel').hidden;renderTrace();};$('#close-trace').onclick=()=>$('#trace-panel').hidden=true;
$('#show-library').onclick=()=>document.body.classList.add('library-open');$('#close-library').onclick=()=>document.body.classList.remove('library-open');$('#library-search').oninput=renderLibrary;
$('#open-help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();$('#open-board-menu').onclick=()=>{renderSnapshots();$('#board-dialog').showModal();};$('#close-dialog').onclick=()=>$('#board-dialog').close();
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportBoard(){try{download(S.exportJSON(snapshotBoard()),'mad-money-board.json');}catch(e){toast(e.message);}}
$('#export-board').onclick=exportBoard;$('#conflict-export').onclick=exportBoard;$('#reload-saved').onclick=()=>{if(roomConflicts){board=clone(roomConflicts.board);roomConflicts=null;$('#conflict-banner').hidden=true;render();scheduleSave();}else{const saved=S.load();if(saved){board=saved;render();$('#conflict-banner').hidden=true;saveLabel('Saved locally');}}};
$('#recover-board').onclick=()=>{try{const raw=localStorage.getItem('mmt-whiteboard-recovery');if(!raw){toast('No shared draft is stored in this browser.');return;}const r=S.importJSON(raw);if(!r.ok)throw Error(r.errors.join(' '));pause();client?.dispose();client=null;room=null;roomConflicts=null;window.history.replaceState(null,'',location.href.split('#')[0]);transact(()=>board=r.board);roomUI();fit();$('#board-dialog').close();toast('Opened the shared draft as a local copy.');}catch(e){toast(e.message);}};
$('#import-board').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>5000000){toast('Board file is too large.');return;}const r=S.importJSON(await f.text());if(!r.ok){$('#dialog-status').textContent=r.errors.join(' ');return;}pause();transact(()=>board=r.board);fit();$('#board-dialog').close();e.target.value='';};
$('#save-snapshot').onclick=()=>{const r=S.saveSnapshot(snapshotBoard(),board.title+' · '+evaluation.currentTime);$('#dialog-status').textContent=r.message;renderSnapshots();};
function renderSnapshots(){const rows=S.listSnapshots();$('#snapshots').innerHTML='<h3>Local checkpoints</h3>'+rows.map(r=>`<div class="snapshot-row"><button data-load-snapshot="${esc(r.id)}"><b>${esc(r.title)}</b><small>${new Date(r.savedAt).toLocaleString()}</small></button><button data-remove-snapshot="${esc(r.id)}" aria-label="Delete checkpoint">×</button></div>`).join('');}
$('#snapshots').onclick=e=>{const load=e.target.closest('[data-load-snapshot]'),del=e.target.closest('[data-remove-snapshot]');if(load){const r=S.loadSnapshot(load.dataset.loadSnapshot);if(r.ok){pause();transact(()=>board=r.board);fit();$('#board-dialog').close();}}if(del){S.deleteSnapshot(del.dataset.removeSnapshot);renderSnapshots();}};
$('#new-board').onclick=()=>{const saved=S.saveSnapshot(snapshotBoard(),'Before reset · '+board.title);if(!saved.ok){$('#dialog-status').textContent='Export this board before resetting; checkpoint failed.';return;}pause();transact(()=>board=M.seedBoard());setView('systems');$('#board-dialog').close();};
document.addEventListener('keydown',e=>{const editing=e.target.closest('input,textarea,select,[contenteditable]');if(e.key==='Escape'){setTool('select');from=null;$('#trace-panel').hidden=true;closeInspector();return;}if(editing||$('dialog[open]'))return;if(e.key==='Enter'&&e.target.matches('[data-node]')){if(tool==='connect')connect(e.target.dataset.node);else select(e.target.dataset.node);return;}if(e.code==='Space'){space=true;e.preventDefault();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelection();}if(e.key.toLowerCase()==='v')setTool('select');if(e.key.toLowerCase()==='c')setTool('connect');if(e.key.toLowerCase()==='p')setTool('pen');if(e.key.toLowerCase()==='f')fit();if(selected&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=getNode(selected),p=position(n),d=e.shiftKey?40:10;transact(()=>setPosition(n,{x:p.x+(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0),y:p.y+(e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0)}));}});
document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;endDrag();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();save();}});window.addEventListener('beforeunload',()=>{if(!room)S.save(snapshotBoard());});S.subscribe(()=>{if(!room){pause();$('#conflict-banner').hidden=false;saveLabel('Changed in another tab',true);}});
function showConflict(){pause();$('#conflict-banner').hidden=false;$('#keep-my-edits').hidden=!room;saveLabel('Shared edit conflict',true);toast('Another editor changed the same field. Export your changes or load the shared board.');}
// Room integration is installed after the canvas is ready.
window.MMTWhiteboard={get board(){return clone(board);},get evaluation(){return evaluation;},get view(){return view;},setView,fit,select,act,addCard,get viewport(){return clone(vp);},get saved(){return clone(lastSaved);}};
document.body.dataset.view=view;renderLibrary();render();transform();requestAnimationFrame(()=>{if(!S.load())fit();});saveLabel(S.getStatus().message||'Local board');if(!S.load())scheduleSave();
const roomDialog=document.createElement('dialog');roomDialog.className='board-dialog';roomDialog.id='room-dialog';roomDialog.setAttribute('aria-label','Shared workshop');roomDialog.innerHTML=`<div class="dialog-header"><h2>Shared workshop</h2><button id="close-room" aria-label="Close sharing">×</button></div><div class="room-fields"><label>Your name<input id="participant-name" maxlength="48" placeholder="Name shown beside your cursor"></label></div><p class="room-members" id="room-members">Local board</p><div class="room-controls"><button id="create-room" class="primary">Create shared room</button><button id="copy-room" hidden>Copy edit link</button><button id="leave-room" hidden>Leave room</button></div><input class="room-link" id="room-link" readonly aria-label="Room edit link" hidden><p id="room-status" role="status"></p><p class="room-caption">Anyone with the edit link can change this board. Shared saves use Supabase; exported files contain no room key.</p><details id="connection-setup"><summary>Supabase connection</summary><div class="room-fields"><label>Project URL<input id="supabase-url" type="url" placeholder="https://your-project.supabase.co"></label><label>Public publishable key<input id="supabase-key" type="text" autocomplete="off" placeholder="sb_publishable_…"></label></div><div class="room-controls"><button id="save-connection">Save connection</button><button id="copy-setup">Copy database setup SQL</button><a href="supabase.sql" download>Download SQL ↓</a></div><p class="setup-note">Run the SQL once in this project’s Supabase SQL Editor. Use a publishable or anon key here. Service-role keys are not accepted.</p></details>`;document.body.append(roomDialog);
let connection={url:'',publishableKey:''};try{connection=JSON.parse(localStorage.getItem('mmt-whiteboard-connection')||'null')||window.MMTWhiteboardConfig||connection;$('#participant-name').value=localStorage.getItem('mmt-whiteboard-name')||'';}catch{}const params=new URLSearchParams(location.hash.slice(1));if(params.get('url')&&params.get('api'))connection={url:params.get('url'),publishableKey:params.get('api')};$('#supabase-url').value=connection.url||'';$('#supabase-key').value=connection.publishableKey||'';$('#connection-setup').open=!connection.url;let entering=false;
function readConnection(){const url=$('#supabase-url').value.trim().replace(/\/$/,''),publishableKey=$('#supabase-key').value.trim();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url))throw Error('Enter the project URL from Supabase.');if(publishableKey.startsWith('sb_secret_'))throw Error('Use a public publishable key, not a secret key.');let valid=publishableKey.startsWith('sb_publishable_');if(publishableKey.split('.').length===3){try{valid=JSON.parse(atob(publishableKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon';}catch{}}if(!valid)throw Error('Use the project’s public publishable or legacy anon key.');connection={url,publishableKey};try{localStorage.setItem('mmt-whiteboard-connection',JSON.stringify(connection));localStorage.setItem('mmt-whiteboard-name',$('#participant-name').value.trim());}catch{}return connection;}
function roomLink(){if(!room)return'';const p=new URLSearchParams({room:room.roomId,key:room.editKey,url:connection.url,api:connection.publishableKey});return location.href.split('#')[0]+'#'+p.toString();}
function roomUI(){$('#create-room').hidden=!!room;$('#copy-room').hidden=!room;$('#leave-room').hidden=!room;$('#room-link').hidden=!room;$('#room-link').value=roomLink();$('#room-members').textContent=room?'Shared room · '+Math.max(1,peers.length)+' present':'Local board';$('#open-room').textContent=room?'Shared · '+Math.max(1,peers.length):'Share';$('#storage-note').textContent=room?'This room saves to Supabase. Checkpoints and JSON exports are separate copies.':'Changes save in this browser. Export a board file to share or back it up.';}
function renderPeers(){for(const el of $$('.live-cursor'))el.remove();for(const p of peers){if(p.clientId===client?.getClientId())continue;if(p.view!==view||!Number.isFinite(p.x)||!Number.isFinite(p.y))continue;const el=document.createElement('div');el.className='live-cursor';el.style.left=p.x+'px';el.style.top=p.y+'px';el.innerHTML='<svg viewBox="0 0 18 20" aria-hidden="true"><path d="M1 1L15 11L8 12L5 18z" fill="#f3a9cf" stroke="#161616"/></svg><span>'+esc(p.name||'Guest')+'</span>';world.append(el);}roomUI();}
function onShared(event){if(event.participants){peers=event.participants;renderPeers();}if(event.type==='board'){if(entering)return;const incoming=event.board;if(MMTBoardCollaboration.diff(snapshotBoard(),incoming).length){board=incoming;if(drag?.kind==='ink')drag.stroke=board.ink.find(s=>s.id===drag.stroke.id)||drag.stroke;history=[];future=[];pause();render();}roomConflicts=null;$('#conflict-banner').hidden=true;}if(event.type==='conflict'){roomConflicts=event;showConflict();}if(event.type==='status'){saveLabel(event.status.message,event.status.state==='offline'||event.status.state==='conflict');}if(event.type==='error'){try{localStorage.setItem('mmt-whiteboard-recovery',S.exportJSON(snapshotBoard()));}catch{}$('#room-status').textContent=event.error;}}
async function enterRoom(join=false){try{pause();const conf=readConnection();client?.dispose();client=MMTBoardCollaboration.createClient({...conf,name:$('#participant-name').value.trim()||'Guest'});client.subscribe(onShared);entering=true;$('#room-status').textContent=join?'Joining room…':'Creating room…';localBeforeRoom=snapshotBoard();const r=join?await client.join({roomId:params.get('room'),editKey:params.get('key'),name:$('#participant-name').value.trim()||'Guest'}):await client.create(snapshotBoard(),{name:$('#participant-name').value.trim()||'Guest'});entering=false;if(!r.ok)throw Error(r.message||(r.errors||[]).join(' ')||'Room could not be opened.');room={roomId:r.roomId,editKey:r.editKey};board=r.board;history=[];future=[];client.presence({view});window.history.replaceState(null,'',roomLink());render();roomUI();$('#room-status').textContent='Shared room ready. Copy the edit link for participants.';saveLabel('Shared · saved');}catch(e){entering=false;$('#room-status').textContent=e.message;$('#room-status').className='room-error';saveLabel(room?'Shared connection failed':'Saved locally',!!room);}}
$('#open-room').onclick=()=>{roomUI();roomDialog.showModal();};$('#close-room').onclick=()=>roomDialog.close();$('#create-room').onclick=()=>enterRoom(false);$('#save-connection').onclick=()=>{try{readConnection();$('#room-status').textContent='Connection saved. Create a room to test database access.';}catch(e){$('#room-status').textContent=e.message;}};$('#participant-name').onchange=()=>{client?.presence({name:$('#participant-name').value.trim()||'Guest'});try{localStorage.setItem('mmt-whiteboard-name',$('#participant-name').value.trim());}catch{}};
async function copyText(text,fallback){try{await navigator.clipboard.writeText(text);toast('Copied');}catch{if(fallback){fallback.hidden=false;fallback.focus();fallback.select();}else toast('Use the download button to get the SQL file.');}}
$('#copy-room').onclick=()=>copyText(roomLink(),$('#room-link'));$('#copy-setup').onclick=async()=>{try{const r=await fetch('supabase.sql');if(!r.ok)throw Error();await copyText(await r.text());}catch{toast('Download the SQL file beside this button.');}};
$('#leave-room').onclick=()=>{pause();S.saveSnapshot(snapshotBoard(),'Shared workshop · '+board.title);client?.dispose();client=null;room=null;peers=[];roomConflicts=null;$('#conflict-banner').hidden=true;window.history.replaceState(null,'',location.href.split('#')[0]);if(localBeforeRoom)board=localBeforeRoom;localBeforeRoom=null;render();renderPeers();roomUI();saveLabel('Local board');$('#room-status').textContent='Shared workshop saved as a local checkpoint.';};
$('#keep-my-edits').onclick=async()=>{if(!client||!roomConflicts)return;roomConflicts=null;const r=await client.resolve('local');if(r.ok){board=r.board;$('#conflict-banner').hidden=true;render();}else{roomConflicts=r;showConflict();}};
$('#reload-saved').onclick=async()=>{if(roomConflicts&&client){const r=await client.resolve('remote');if(r.ok){board=r.board;roomConflicts=null;$('#conflict-banner').hidden=true;render();}}else{const saved=S.load();if(saved){board=saved;render();$('#conflict-banner').hidden=true;saveLabel('Saved locally');}}};
if(params.has('room')){roomDialog.showModal();$('#room-status').textContent='Enter your name, then join this workshop.';const join=document.createElement('button');join.className='primary';join.textContent='Join shared room';join.id='join-room';join.onclick=()=>enterRoom(true);$('.room-controls').prepend(join);$('#create-room').hidden=true;}
})();
