/* Whiteboard adapter. Episode values and proposed graph counters remain separate. */
(function(root){
'use strict';
const clone=value=>JSON.parse(JSON.stringify(value));
const TYPES=[
 {id:'project',label:'Project',group:'Episode',description:'Work, preparation and delivery.',defaults:{params:{},ref:'episode:C-07'}},
 {id:'staff',label:'Staff pool',group:'Episode',description:'Two shared work units per half-day.',defaults:{params:{},ref:'episode:staff'}},
 {id:'supplier',label:'Supplier',group:'Episode',description:'Fabrication release depends on receipt.',defaults:{params:{},ref:'episode:S-08'}},
 {id:'site',label:'Work bay',group:'Episode',description:'Near dock or shared floor changes handoff time.',defaults:{params:{},ref:'episode:work-bay'}},
 {id:'zone',label:'Placement zone',group:'Planning',description:'A destination for the work bay.',defaults:{params:{zone:'near'}}},
 {id:'obligation',label:'Obligation',group:'Episode',description:'Amount committed, independent of the saved payment label.',defaults:{params:{},ref:'episode:O-19'}},
 {id:'payment',label:'Payment attempt',group:'Episode',description:'A dated debit, receipt or return.',defaults:{params:{},ref:'episode:P-04'}},
 {id:'record',label:'Saved record',group:'Episode',description:'A dated snapshot; it does not establish current settlement.',defaults:{params:{},ref:'episode:record-v2'}},
 {id:'approval',label:'Finance approval',group:'Episode',description:'A received trace or recipient reply permits an approval request.',defaults:{params:{},ref:'episode:approval'}},
 {id:'artifact',label:'Artifact',group:'Ideas',description:'A proposed object or document.',defaults:{params:{note:'Describe the object and its use.'}}},
 {id:'archetype',label:'Archetype',group:'Ideas',description:'A proposed role, goal or behavior.',defaults:{params:{note:'Describe the role and its goal.'}}},
 {id:'trigger',label:'Trigger',group:'Rules',description:'Starts a proposed rule chain. Manual, interval, return or delivered.',defaults:{params:{event:'manual'}}},
 {id:'effect',label:'Effect',group:'Rules',description:'Adds to or sets a separate proposal counter.',defaults:{params:{metric:'work',operation:'add',value:1}}},
 {id:'beat',label:'Story beat',group:'Story',description:'A narrative step linked to gameplay objects.',defaults:{params:{mode:'story',order:0,note:'Describe what the player experiences.',references:[]}}},
 {id:'anchor',label:'Gameplay anchor',group:'Structure',description:'A parent group for related story and system objects.',defaults:{params:{mode:'structure',order:0,note:'Describe this part of the game.',references:[]}}},
 {id:'note',label:'Note',group:'Ideas',description:'Free discussion text.',defaults:{params:{note:''}}}
];
const ASSUMPTIONS={startingCash:{key:'startingCash',default:40000,label:'Opening cash'},supplierCost:{key:'supplier',default:12000,label:'Supplier cost'},materialsCost:{key:'materials',default:4000,label:'Materials'},payroll:{key:'payroll',default:6000,label:'Payroll'}};
const EVENTS=['manual','interval','return','delivered'];
const MONEY_MAX=10000000;
function engine(){const e=root.MMTEpisode||(typeof require==='function'?require('../episode-01/model.js'):null);if(!e)throw Error('Load the Episode 01 model before the whiteboard model.');return e;}
function configFor(scenario){const result={},errors=[],custom=[];for(const [name,spec]of Object.entries(ASSUMPTIONS)){let v=scenario?.assumptions?.[name];if(v===undefined||v===null||v==='')v=spec.default;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>MONEY_MAX||Math.abs(v*100-Math.round(v*100))>1e-6){errors.push(spec.label+' must be a dollar amount from 0 to 10,000,000 with at most two decimals.');v=spec.default;}result[spec.key]=Math.round(v*100);if(v!==spec.default)custom.push({key:name,label:spec.label,value:v});}return {values:result,errors,custom};}
function withConfig(scenario,fn){const E=engine(),cfg=configFor(scenario),old={};for(const key of Object.keys(cfg.values)){old[key]=E.CONFIG[key];E.CONFIG[key]=cfg.values[key];}try{return fn(E,cfg);}finally{Object.assign(E.CONFIG,old);}}
function scenarioOf(board){const s=board?.scenario||{};return {plan:['supplier','internal'].includes(s.plan)?s.plan:'supplier',placement:s.placement==='shared'?'shared':'near',mode:s.mode==='ordinary'?'ordinary':'full',crew:s.crew===2?2:1,assumptions:s.assumptions||{}};}
function initial(E,scenario){let s=E.initial(scenario.mode==='full'?'episode':'ordinary');for(const action of [{type:'plan',value:scenario.plan},{type:'bay',value:scenario.placement==='near'?'dock':'studio'},{type:'crew',value:scenario.crew}])s=E.reduce(s,action);return s;}
function seedBoard(){const board={schemaVersion:1,id:'mmt-episode-workshop',title:'Episode 01 · production and payment',nodes:[
 {id:'staff',type:'staff',title:'Shared staff',x:80,y:90,params:{},ref:'episode:staff'},
 {id:'project',type:'project',title:'C-07 · component',x:410,y:90,params:{},ref:'episode:C-07'},
 {id:'other-project',type:'project',title:'Competing display job',x:80,y:345,params:{},ref:'episode:display'},
 {id:'supplier',type:'supplier',title:'S-08 · fabricator',x:745,y:90,params:{},ref:'episode:S-08'},
 {id:'obligation',type:'obligation',title:'O-19 · fabrication',x:745,y:345,params:{},ref:'episode:O-19'},
 {id:'payment',type:'payment',title:'P-04 · funding attempt',x:1080,y:345,params:{},ref:'episode:P-04'},
 {id:'record',type:'record',title:'Saved Paid · v2',x:1080,y:600,params:{},ref:'episode:record-v2'},
 {id:'approval',type:'approval',title:'Reissue permission',x:745,y:600,params:{},ref:'episode:approval'},
 {id:'near-zone',type:'zone',title:'Near dock · 1 interval',x:80,y:655,params:{zone:'near'}},
 {id:'shared-zone',type:'zone',title:'Shared floor · 2 intervals',x:410,y:655,params:{zone:'shared'}},
 {id:'work-bay',type:'site',title:'Work bay',x:95,y:745,params:{},ref:'episode:work-bay'},
 {id:'return-trigger',type:'trigger',title:'When funding returns',x:1420,y:345,params:{event:'return'}},
 {id:'review-effect',type:'effect',title:'Add a review task',x:1420,y:600,params:{metric:'review tasks',operation:'add',value:1}},
 {id:'discussion',type:'note',title:'Discussion',x:1080,y:90,params:{note:'What should happen when a payment returns but the saved record still says Paid?'}}
 ],edges:[
 {id:'staff-project',from:'staff',to:'project',kind:'flow',label:'Assigned work'},
 {id:'staff-other',from:'staff',to:'other-project',kind:'flow',label:'Remaining capacity'},
 {id:'supplier-project',from:'supplier',to:'project',kind:'requires',label:'Supplier release'},
 {id:'obligation-payment',from:'obligation',to:'payment',kind:'flow',label:'Funding attempt'},
 {id:'payment-record',from:'payment',to:'record',kind:'informs',label:'Saved on Tuesday'},
 {id:'payment-approval',from:'payment',to:'approval',kind:'informs',label:'Trace or recipient reply'},
 {id:'payment-return',from:'payment',to:'return-trigger',kind:'informs',label:'Return event'},
 {id:'return-review',from:'return-trigger',to:'review-effect',kind:'flow',label:'Proposed response'},
 {id:'bay-project',from:'work-bay',to:'project',kind:'informs',label:'Handoff time'}
 ],ink:[],viewport:{x:0,y:0,zoom:1},scenario:{plan:'supplier',placement:'near',mode:'full',crew:1},runtime:{actions:[]}};
 const anchors=[
  {id:'anchor-episode',title:'Episode 01',parentId:null,order:0,references:['project','payment'],note:'Produce C-07 while tracking work, cash and records separately.'},
  {id:'anchor-production',title:'Production',parentId:'anchor-episode',order:1,references:['staff','project','other-project','supplier','work-bay'],note:'Shared capacity, supplier release and physical handoff.'},
  {id:'anchor-payments',title:'Payment and records',parentId:'anchor-episode',order:2,references:['obligation','payment','record'],note:'An obligation, a bank event and a saved label have different meanings.'},
  {id:'anchor-recovery',title:'Response and closeout',parentId:'anchor-episode',order:3,references:['approval','return-trigger','review-effect'],note:'Inspect records, secure authority, revise production and explain the outcome.'}
 ];
 for(const a of anchors)board.nodes.push({id:a.id,type:'anchor',title:a.title,x:80+a.order*330,y:1100,params:{mode:'structure',order:a.order,parentId:a.parentId,references:a.references,note:a.note}});
 const beats=[
  {id:'story-brief',title:'Accept the component brief',parentId:'anchor-production',condition:'brief',references:['project','other-project'],note:'C-07 is due Thursday PM. A competing display needs three staff units by Tuesday PM.'},
  {id:'story-production',title:'Choose the production plan',parentId:'anchor-production',condition:'production',references:['project','staff','supplier','work-bay'],note:'Build in-house or commission S-08. Staff allocation and bay placement determine the physical schedule.'},
  {id:'story-paid',title:'Read the saved Paid record',parentId:'anchor-payments',condition:'saved-paid',references:['payment','record','obligation'],note:'The supplier route posts a Tuesday debit and saves Paid v2. That snapshot is not recipient confirmation.'},
  {id:'story-return',title:'Funding returns',parentId:'anchor-payments',condition:'funding-return',references:['payment','record','obligation','return-trigger'],note:'The full supplier route returns funding Wednesday AM. Posted cash recovers; O-19 remains open.'},
  {id:'story-recovery',title:'Choose a response',parentId:'anchor-recovery',condition:'recovery',references:['approval','supplier','project'],note:'Request records, seek reissue authority, build a substitute or revise the handoff.'},
  {id:'story-delivery',title:'Deliver and explain the outcome',parentId:'anchor-recovery',condition:'delivery',references:['project','other-project','obligation'],note:'Compare delivery, the competing job, posted and reserved cash, and any unresolved supplier obligation.'}
 ];
 for(let i=0;i<beats.length;i++){const b=beats[i];board.nodes.push({id:b.id,type:'beat',title:b.title,x:80+i*330,y:1450,params:{mode:'story',order:i+1,parentId:b.parentId,references:b.references,note:b.note,condition:b.condition}});if(i)board.edges.push({id:beats[i-1].id+'-'+b.id,from:beats[i-1].id,to:b.id,kind:'informs',label:'Story order'});}
 const groups={'anchor-production':['staff','project','other-project','supplier','work-bay','near-zone','shared-zone'],'anchor-payments':['obligation','payment','record'],'anchor-recovery':['approval','return-trigger','review-effect'],'anchor-episode':['discussion']};
 for(const [parentId,ids]of Object.entries(groups))for(let order=0;order<ids.length;order++){const n=board.nodes.find(n=>n.id===ids[order]);n.params={...n.params,parentId,order};}
 return board;
}
function beatState(node,s,E){const p=node.params||{},supplier=s.plan==='supplier',returned=supplier&&s.mode==='episode';let state='proposed';switch(p.condition){case 'brief':state=s.started?'reached':'current';break;case 'production':state=s.started?'reached':'pending';break;case 'saved-paid':state=!supplier?'not-in-run':s.documents.includes('v2')?'reached':'pending';break;case 'funding-return':state=!returned?'not-in-run':s.returned?'reached':'pending';break;case 'recovery':state=!returned?'not-in-run':!s.returned?'pending':s.reissue||s.substitute||Object.keys(s.requests).length?'reached':'current';break;case 'delivery':state=s.delivered!==null?'reached':E.ready(s)?'current':'pending';break;}return {state,detail:p.note||'Proposed narrative step.',ready:state==='reached',scope:'proposal',references:Array.isArray(p.references)?p.references:[]};}

function isReference(node){return typeof node.ref==='string'&&node.ref.startsWith('episode:');}
function refId(node){return typeof node.ref==='string'?node.ref.replace(/^episode:/,''):'';}
function nodeState(node,s,E){if(node.type==='beat')return beatState(node,s,E);if(node.type==='anchor')return {state:'structure',detail:node.params?.note||'Gameplay group.',ready:false,scope:'proposal',references:node.params?.references||[]};const id=refId(node),base={state:'proposed',detail:'Discussion element; no Episode 01 rule is attached.',ready:false,scope:'proposal'};
 switch(id){
 case 'C-07':return {state:s.delivered!==null?'complete':E.ready(s)?'ready':s.returned&&!s.substitute&&!s.supplierSettled?'held':'working',detail:E.stage(s),metrics:{work:s.work,prep:s.prep,handoff:s.handoff},ready:s.delivered!==null,scope:'episode'};
 case 'display':return {state:s.other===0?'complete':s.turn>=E.CONFIG.otherDue?'late':'working',detail:s.other===0?'Finished '+E.DAYS[s.otherDone]:s.other+' work units left · due Tue PM',metrics:{remaining:s.other},ready:s.other===0,scope:'episode'};
 case 'staff':return {state:'assigned',detail:s.crew+' unit'+(s.crew===1?'':'s')+' to C-07 · '+(E.CONFIG.capacity-s.crew)+' to display',metrics:{capacity:E.CONFIG.capacity,crew:s.crew},ready:true,scope:'episode'};
 case 'work-bay':return {state:'placed',detail:s.bay==='dock'?'Near dock · 1 handoff interval':'Shared floor · 2 handoff intervals',metrics:{handoffIntervals:s.bay==='dock'?1:2},ready:true,scope:'episode'};
 case 'S-08':return {state:s.plan==='internal'?'unused':s.supplierSettled?'released':s.returned?'held':'awaiting',detail:s.plan==='internal'?'Internal production selected':s.supplierSettled?'Recipient receipt confirmed':s.returned?'Funding returned; component held':'Release requires recipient receipt',ready:s.supplierSettled,scope:'episode'};
 case 'O-19':return {state:s.plan==='internal'?'unused':s.supplierSettled?'settled':'open',detail:s.plan==='internal'?'No supplier obligation created':E.money(E.CONFIG.supplier)+(s.supplierSettled?' · receipt confirmed':' · obligation remains open'),metrics:{amount:s.plan==='internal'?0:E.CONFIG.supplier},ready:s.supplierSettled,scope:'episode'};
 case 'P-04':return {state:s.plan==='internal'?'unused':s.returned?'returned':s.mode==='ordinary'&&s.supplierSettled?'received':s.turn>=2?'debited':s.turn>=1?'scheduled':'planned',detail:s.plan==='internal'?'No P-04 attempt':s.returned?'Original attempt returned Wed AM':s.mode==='ordinary'&&s.supplierSettled?'Recipient confirmed Tue PM':s.turn>=2?'Funding debit posted Tue AM':s.turn>=1?'Scheduled Monday PM':'Not yet scheduled',ready:s.plan==='supplier'&&s.mode==='ordinary'&&s.supplierSettled,scope:'episode'};
 case 'P-05':return {state:s.reissue?(s.supplierSettled?'received':'debited'):'not-created',detail:s.reissue?(s.supplierSettled?'Separate reissue received':'Approved reissue debit posted'):'Requires one finance approval',ready:!!s.reissue&&s.supplierSettled,scope:'episode'};
 case 'record-v2':return {state:s.documents.includes('v2')?'available':'unavailable',detail:s.documents.includes('v2')?'Paid · saved Tue 10:02 · not a later observation':'Available after Tuesday funding debit',ready:s.documents.includes('v2'),scope:'episode'};
 case 'approval':return {state:s.reissue?'used':s.approved?'granted':s.requests.approval?.status==='pending'?'requested':'needed',detail:s.reissue?'One reissue instruction used':s.approved?'One unused reissue instruction':s.requests.approval?.status==='pending'?'Finance reply due next interval':'Request after a received trace or recipient reply',ready:s.approved&&!s.reissue,scope:'episode'};
 case 'bank':return {state:'current',detail:E.money(s.cash)+' posted · '+E.money(E.available(s))+' available',metrics:{posted:s.cash,available:E.available(s)},ready:true,scope:'episode'};
 default:if(node.type==='zone')return {state:'zone',detail:node.params?.zone==='shared'?'Two handoff intervals':'One handoff interval',ready:false,scope:'layout'};if(node.type==='trigger')return {...base,state:'armed',detail:'On '+(EVENTS.includes(node.params?.event)?node.params.event:'manual')};if(node.type==='effect')return {...base,state:'rule',detail:'Proposal counter: '+(node.params?.metric||'work')};return {...base,detail:node.params?.note||base.detail};
 }}
function graph(board){const nodes=new Map(),duplicates=[];for(const n of (board.nodes||[]).slice(0,500)){if(!n||typeof n.id!=='string')continue;if(nodes.has(n.id)){duplicates.push(n.id);continue;}nodes.set(n.id,n);}const edges=(board.edges||[]).filter(e=>e&&typeof e.id==='string').slice(0,1500),valid=edges.filter(e=>nodes.has(e.from)&&nodes.has(e.to)),flow=valid.filter(e=>e.kind==='flow'),incoming=new Map(),outgoing=new Map();for(const id of nodes.keys()){incoming.set(id,[]);outgoing.set(id,[]);}for(const e of valid){incoming.get(e.to).push(e);outgoing.get(e.from).push(e);}return {nodes,edges,valid,flow,incoming,outgoing,duplicates};}
function components(g){let index=0;const ix=new Map(),low=new Map(),stack=[],on=new Set(),result=[];function visit(id){ix.set(id,index);low.set(id,index++);stack.push(id);on.add(id);for(const e of g.outgoing.get(id)||[]){if(e.kind!=='flow')continue;if(!ix.has(e.to)){visit(e.to);low.set(id,Math.min(low.get(id),low.get(e.to)));}else if(on.has(e.to))low.set(id,Math.min(low.get(id),ix.get(e.to)));}if(low.get(id)===ix.get(id)){const part=[];let t;do{t=stack.pop();on.delete(t);part.push(t);}while(t!==id);if(part.length>1||g.flow.some(e=>e.from===id&&e.to===id))result.push(part);}}for(const id of g.nodes.keys())if(!ix.has(id))visit(id);return result;}
function experiment(g){return {counters:Object.create(null),fired:new Set(),usedEdges:new Set(),blocked:new Map(),trace:[],visits:{},lastFired:new Set(),pulses:0};}
function dispatch(g,ex,event,s,E,nodeId){const roots=[...g.nodes.values()].filter(n=>n.type==='trigger'&&((event==='manual'&&n.id===nodeId)||(event!=='manual'&&n.params?.event===event)));for(const start of roots){const queue=[start.id],visited=new Set(),deferred=new Map();let passes=0;ex.pulses++;while(queue.length&&passes++<g.nodes.size*3){const id=queue.shift();if(visited.has(id))continue;const n=g.nodes.get(id);if(!n||!['trigger','effect'].includes(n.type))continue;const requirements=(g.incoming.get(id)||[]).filter(e=>e.kind==='requires');const missing=requirements.filter(e=>{const source=g.nodes.get(e.from);return isReference(source)?!nodeState(source,s,E).ready:!visited.has(source.id);});if(missing.length){deferred.set(id,missing);continue;}deferred.delete(id);ex.blocked.delete(id);visited.add(id);ex.fired.add(id);ex.lastFired.add(id);ex.visits[id]=(ex.visits[id]||0)+1;ex.trace.push({nodeId:id,text:(n.title||id)+' · '+event+' at '+E.DAYS[s.turn],scope:'proposal',turn:s.turn});for(const e of requirements)ex.usedEdges.add(e.id);
 if(n.type==='effect'){const p=n.params||{},metric=typeof p.metric==='string'&&p.metric.trim()?p.metric.trim().slice(0,48):'work',v=p.value,op=p.operation||'add';if(typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=100000&&['add','set'].includes(op)){const old=ex.counters[metric]||0;ex.counters[metric]=Math.max(-100000000,Math.min(100000000,op==='set'?v:old+v));}else{ex.blocked.set(id,'Effect needs add/set and a finite value from −100,000 to 100,000.');}}
 for(const e of g.outgoing.get(id)||[])if(e.kind==='flow'&&['trigger','effect'].includes(g.nodes.get(e.to)?.type)){ex.usedEdges.add(e.id);queue.push(e.to);}for(const pending of deferred.keys())queue.push(pending);
 }for(const [id,missing]of deferred)ex.blocked.set(id,'Requires '+missing.map(e=>g.nodes.get(e.from)?.title||e.from).join(', '));}}
function actionsFor(s,E,g){const candidates=[{id:'advance',label:'Next half-day',action:{type:'advance'}},{id:'trace',label:'Request processor trace',action:{type:'request',value:'processor'}},{id:'recipient',label:'Request recipient reply',action:{type:'request',value:'recipient'}},{id:'invoice',label:'Request invoice export',action:{type:'request',value:'invoice'}},{id:'approval',label:'Request finance approval',action:{type:'request',value:'approval'}},{id:'reissue',label:'Send approved reissue',action:{type:'reissue'}},{id:'substitute',label:'Build a substitute',action:{type:'substitute'}},{id:'delay',label:'Request Friday handoff',action:{type:'request',value:'delay'}},{id:'batch',label:'Reconcile the $2,000 batch',action:{type:'poolAnswer',value:200000}}];const list=candidates.filter(c=>{if(c.action.type==='request'&&s.requests[c.action.value])return false;if(c.id==='batch'&&s.poolAnswer===200000)return false;try{E.reduce(s,c.action);return true;}catch{return false;}});for(const n of g.nodes.values())if(n.type==='trigger'&&(n.params?.event||'manual')==='manual')list.push({id:'fire:'+n.id,label:'Fire '+(n.title||'trigger'),action:{type:'fire',nodeId:n.id}});return list;}
function run(board,scenario,E,cfg){const g=graph(board),signals=[],trace=[],ex=experiment(g);let s,invalidFrom=null,configurationBlocked=false;try{s=initial(E,scenario);}catch(error){s=E.initial(scenario.mode==='full'?'episode':'ordinary');invalidFrom=0;configurationBlocked=true;signals.push({severity:'error',title:'The plan exceeds opening cash',detail:error.message+'. Increase opening cash or reduce commitments before starting.',nodeIds:[]});}const actions=Array.isArray(board.runtime?.actions)?board.runtime.actions:[];
 for(let i=0;!configurationBlocked&&i<Math.min(actions.length,500);i++){const a=actions[i],old=s;if(!a||typeof a.type!=='string'){invalidFrom=i;signals.push({severity:'error',title:'Invalid saved action',detail:'Action '+(i+1)+' has no action type. Restart the run to continue.',nodeIds:[]});break;}try{if(a.type==='fire'){const n=g.nodes.get(a.nodeId);if(!n||n.type!=='trigger')throw Error('The manual trigger is no longer on this board.');if((n.params?.event||'manual')!=='manual')throw Error('Only manual triggers can be fired directly.');dispatch(g,ex,'manual',s,E,a.nodeId);}else{if(!['advance','request','reissue','substitute','crew','poolAnswer'].includes(a.type))throw Error('Unsupported timeline action '+a.type);s=E.reduce(s,a);if(a.type==='advance'){dispatch(g,ex,'interval',s,E);if(!old.returned&&s.returned)dispatch(g,ex,'return',s,E);if(old.delivered===null&&s.delivered!==null)dispatch(g,ex,'delivered',s,E);}}}catch(error){invalidFrom=i;signals.push({severity:'warning',title:'Replay stops at action '+(i+1),detail:error.message+' Restart the run or undo this action before continuing.',nodeIds:[]});break;}}
 if(actions.length>500)signals.push({severity:'warning',title:'Action limit reached',detail:'Only the first 500 actions were replayed.',nodeIds:[]});
 for(const error of cfg.errors)signals.push({severity:'error',title:'Invalid assumption',detail:error+' The episode default is shown.',nodeIds:[]});
 if(cfg.custom.length)signals.push({severity:'info',title:'Custom workshop assumptions',detail:cfg.custom.map(x=>x.label+' '+E.money(Math.round(x.value*100))).join(' · ')+'. These change this sandbox only.',nodeIds:[]});
 const states=Object.create(null);for(const [id,n]of g.nodes){states[id]=nodeState(n,s,E);if(ex.fired.has(id))states[id]={...states[id],state:'fired',detail:n.type==='effect'?'Proposal '+(n.params?.metric||'work')+': '+(ex.counters[n.params?.metric||'work']??0):ex.visits[id]+' activation'+(ex.visits[id]===1?'':'s'),ready:true};if(ex.blocked.has(id))states[id]={...states[id],state:'blocked',detail:ex.blocked.get(id),ready:false};}
 const edgeStates=Object.create(null);for(const e of g.edges){const a=g.nodes.get(e.from),b=g.nodes.get(e.to),valid=!!a&&!!b,operative=valid&&e.kind==='flow'&&['trigger','effect'].includes(a.type)&&['trigger','effect'].includes(b.type),requirement=valid&&e.kind==='requires'&&['trigger','effect'].includes(b.type),blocked=requirement&&!states[e.from].ready;edgeStates[e.id]={active:ex.usedEdges.has(e.id)||(valid&&e.kind==='informs'&&states[e.from].ready),blocked,scope:operative||requirement?'proposal-rule':'diagram',detail:!valid?'Endpoint missing':operative?'Runs the proposed rule chain':requirement?'Guard for proposed rule':e.kind==='informs'?'Information link; no economic effect':'Discussion connection; Episode 01 rules remain defined in its model'};}
 for(const e of g.edges)if(!g.nodes.has(e.from)||!g.nodes.has(e.to))signals.push({severity:'warning',title:'Connection has a missing endpoint',detail:e.label||e.id,nodeIds:[e.from,e.to].filter(id=>g.nodes.has(id))});
 for(const id of g.duplicates)signals.push({severity:'error',title:'Duplicate object ID',detail:id+' appears more than once. Only its first occurrence is evaluated.',nodeIds:[id]});
 const isolated=[...g.nodes.values()].filter(n=>!['note','zone','beat','anchor'].includes(n.type)&&!(g.incoming.get(n.id)||[]).length&&!(g.outgoing.get(n.id)||[]).length);if(isolated.length)signals.push({severity:'info',title:'Unconnected objects',detail:isolated.map(n=>n.title||n.id).join(', ')+'. Connect them to describe their role.',nodeIds:isolated.map(n=>n.id)});
 for(const n of g.nodes.values()){if(n.params?.parentId&&!g.nodes.has(n.params.parentId))signals.push({severity:'warning',title:'Missing parent group',detail:(n.title||n.id)+' refers to '+n.params.parentId+'.',nodeIds:[n.id]});const missing=(Array.isArray(n.params?.references)?n.params.references:[]).filter(id=>!g.nodes.has(id));if(missing.length)signals.push({severity:'warning',title:'Missing gameplay reference',detail:(n.title||n.id)+': '+missing.join(', '),nodeIds:[n.id]});}
 const reportedParents=new Set();for(const n of g.nodes.values()){const seen=new Set(),chain=[];let at=n;while(at&&at.params?.parentId){if(seen.has(at.id)){const ids=chain.slice(chain.indexOf(at.id));const key=ids.slice().sort().join('|');if(!reportedParents.has(key)){reportedParents.add(key);signals.push({severity:'warning',title:'Hierarchy contains a loop',detail:'A group cannot contain itself through another parent.',nodeIds:ids});}break;}seen.add(at.id);chain.push(at.id);at=g.nodes.get(at.params.parentId);}}
 const cycles=components(g);for(const ids of cycles){const upstream=new Set(ids),queue=[...ids];while(queue.length){const id=queue.shift();for(const e of g.incoming.get(id)||[])if(e.kind==='flow'&&!upstream.has(e.from)){upstream.add(e.from);queue.push(e.from);}}const triggered=[...upstream].some(id=>g.nodes.get(id)?.type==='trigger');signals.push({severity:triggered?'info':'warning',title:triggered?'Bounded rule loop':'Loop has no trigger',detail:triggered?'Each node can run once per trigger pulse. A new event starts the next pass.':'This loop describes a relationship but cannot start a proposed rule. Add an explicit trigger.',nodeIds:ids});}
 for(const [id,detail]of ex.blocked)signals.push({severity:'warning',title:'Proposed rule blocked',detail,nodeIds:[id]});
 const refNodes=id=>[...g.nodes.values()].filter(n=>refId(n)===id).map(n=>n.id);
 if(s.crew===2&&s.other>0)signals.push({severity:'warning',title:'The display job has no staff',detail:'Both work units are assigned to C-07. The competing job cannot advance.',nodeIds:[...refNodes('staff'),...refNodes('display')]});
 if(s.bay==='studio')signals.push({severity:'info',title:'Shared floor adds one handoff interval',detail:'The physical handoff takes two intervals after work and supplier release are ready. It does not change bank timing.',nodeIds:refNodes('work-bay')});
 if(s.returned)signals.push({severity:s.supplierSettled?'info':'warning',title:'P-04 returned; saved Paid v2 is unchanged',detail:s.supplierSettled?'P-05 has separate receipt confirmation. The original P-04 attempt remains returned.':'The return restores posted cash. It does not settle O-19 or update Tuesday’s saved snapshot.',nodeIds:[...refNodes('P-04'),...refNodes('record-v2'),...refNodes('O-19')]});
 if(s.substitute&&!s.supplierSettled)signals.push({severity:'warning',title:'Substitute work does not clear O-19',detail:'Materials and capacity are additional costs. The supplier obligation remains open.',nodeIds:[...refNodes('C-07'),...refNodes('O-19')]});
 if(s.turn>=E.CONFIG.otherDue&&s.otherDone===null)signals.push({severity:'warning',title:'Display handoff missed',detail:s.other+' work units still needed after Tuesday PM.',nodeIds:refNodes('display')});
 if(s.turn>=s.promise&&s.delivered===null)signals.push({severity:'warning',title:'C-07 handoff missed',detail:'The current promise was '+E.DAYS[s.promise]+'.',nodeIds:refNodes('C-07')});
 trace.push(...s.events.map(e=>({nodeId:refNodes(e.kind==='cash'?'P-04':e.kind==='record'?'record-v2':'C-07')[0]||null,text:e.text,turn:e.turn,time:E.DAYS[e.turn],scope:'episode'})),...ex.trace);trace.sort((a,b)=>a.turn-b.turn);
 const stats=[{key:'posted',label:'Posted cash',value:E.money(s.cash),unit:'USD',raw:s.cash},{key:'committed',label:'Reserved cash',value:E.money(E.committed(s)),unit:'USD',raw:E.committed(s)},{key:'available',label:'Available cash',value:E.money(E.available(s)),unit:'USD',raw:E.available(s)},{key:'work',label:'C-07 work left',value:String(s.work+s.prep),unit:'units',raw:s.work+s.prep},{key:'other',label:'Display work left',value:String(s.other),unit:'units',raw:s.other},{key:'delivery',label:'C-07 delivery',value:s.delivered===null?'Pending':E.DAYS[s.delivered],raw:s.delivered,unit:'half-day'}];
 for(const [key,value]of Object.entries(ex.counters))stats.push({key:'proposal:'+key,label:'Proposal · '+key,value:String(value),unit:'counter',raw:value,scope:'proposal'});
 return {nodes:states,edges:edgeStates,stats,signals,trace,configurationBlocked,episode:clone(s),availableActions:invalidFrom===null?actionsFor(s,E,g):[],currentTime:E.DAYS[s.turn],turn:s.turn,invalidFrom,customAssumptions:cfg.custom,proposal:{counters:ex.counters,pulses:ex.pulses,visits:ex.visits},outcome:E.outcome(s)};
}
function evaluate(board){if(!board||typeof board!=='object')throw Error('A board is required.');const scenario=scenarioOf(board);return withConfig(scenario,(E,cfg)=>{const output=run(board,scenario,E,cfg);const baselineBoard={...board,scenario:{...scenario,assumptions:{}},nodes:board.nodes||[],edges:[]};const baseline=withConfig({...scenario,assumptions:{}},(engine,config)=>run(baselineBoard,{...scenario,assumptions:{}},engine,config));output.baseline={stats:baseline.stats,turn:baseline.turn,invalidFrom:baseline.invalidFrom};output.stats=output.stats.map(stat=>{const b=baseline.stats.find(x=>x.key===stat.key);return {...stat,baselineRaw:b?.raw,delta:typeof stat.raw==='number'&&typeof b?.raw==='number'&&baseline.turn===output.turn?stat.raw-b.raw:null};});return output;});}
function step(board,action){if(!action||typeof action.type!=='string')throw Error('Choose an action.');const next=clone(board);next.runtime=next.runtime||{};if(action.type==='reset'){next.runtime.actions=[];return next;}if((next.runtime.actions||[]).length>=500)throw Error('This board has reached 500 actions. Export it, then restart the timeline.');const before=evaluate(board);if(before.invalidFrom!==null)throw Error('The saved run no longer fits these rules. Restart the timeline or undo the blocked action.');if(action.type==='fire'){const n=(board.nodes||[]).find(n=>n.id===action.nodeId);if(!n||n.type!=='trigger'||(n.params?.event||'manual')!=='manual')throw Error('Choose a manual trigger.');}else{const scenario=scenarioOf(board);withConfig(scenario,E=>E.reduce(before.episode,action));if(!['advance','request','reissue','substitute','crew','poolAnswer'].includes(action.type))throw Error('Unsupported timeline action.');}next.runtime.actions=[...(next.runtime.actions||[]),clone(action)];return next;}
const API={seedBoard,types:TYPES,evaluate,step,assumptions:clone(ASSUMPTIONS),events:EVENTS.slice(),scenarioOf};root.MMTBoardModel=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof window==='undefined'?globalThis:window);
