(()=>{'use strict';
const E=window.MMTEpisode,$=id=>document.getElementById(id),cash=E.money,C=E.CONFIG,key='mmt-episode-01-v1';
let s=E.initial(),auto=null,scenery=!matchMedia('(prefers-reduced-motion: reduce)').matches,t=0,last=0,hits=[],doc=null;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.schema===1&&Array.isArray(saved.actions)){s=saved.actions.reduce((state,a)=>E.reduce(state,a),E.initial(saved.mode));}}catch{}
function persist(){try{localStorage.setItem(key,JSON.stringify(s));}catch{}}
function stop(){clearInterval(auto);auto=null;$('auto').textContent='Run schedule';}
function dispatch(a){try{const before=s.events.length;s=E.reduce(s,a);persist();$('notice').textContent='';if(a.type==='advance'&&(s.finished||s.events.slice(before).some(e=>['notice','record','control'].includes(e.kind))))stop();render();return true;}catch(e){stop();$('notice').textContent=e.message;return false;}}
const button=(label,type,value,extra='')=>`<button data-action="${type}"${value===undefined?'':` data-value="${value}"`} ${extra}>${label}</button>`;
const row=(a,b)=>`<tr><td>${a}</td><td>${b}</td></tr>`;
function workView(){const other=s.selection==='OTHER';return `<h3>${other?'Display job':E.stage(s)}</h3><div class="stage-track">${other?`<div class="${!s.other?'done':''}"><b>FABRICATION</b><span>${3-s.other} / 3 units</span></div><div><b>RESERVATION</b><span>Tue PM</span></div><div><b>HANDOFF</b><span>${s.otherDone===null?'Not complete':E.DAYS[s.otherDone]}</span></div>`:`<div class="${s.started&&!s.work?'done':''}"><b>01 / MAKE</b><span>${!s.plan?'Choose a plan':s.work?`${s.work} units remain`:s.plan==='supplier'&&!s.substitute?'Supplier component':'Fabricated'}</span></div><div class="${!s.prep?'done':''}"><b>02 / CHECK & PACK</b><span>${s.prep} units remain</span></div><div class="${s.delivered!==null?'done':''}"><b>03 / HAND OFF</b><span>${s.delivered!==null?E.DAYS[s.delivered]:s.plan==='supplier'&&!s.substitute&&!s.supplierSettled?'Await supplier release':`${s.handoff} / ${s.bay==='dock'?1:2} intervals`}</span></div>`}</div><p class="legend">${other?'Staff allocation is shared with C-07. A missed reservation is retained in the outcome.':`Current promise: ${E.DAYS[s.promise]}. ${s.delayApproved?'Original promise: Thu PM. ':''}Budget ceiling: $100,000; no client cash has arrived.`}</p>`;}
function view(){
if(s.view==='Work')return workView();
if(s.selection==='OTHER'){
 if(s.view==='Cash')return `<h3>Display job / shared cash</h3><table>${row('Separate materials charge','None modeled')}${row('Shared Friday payroll','$6,000')}${row('Shared posted bank cash',cash(s.cash))}</table><p class="legend">Payroll belongs to the shared staff pool; it is not charged a second time to this job. O-19 belongs to C-07's supplier plan.</p>`;
 if(s.view==='Information')return `<h3>Display job / current record</h3><div class="info-grid"><div><span>OBJECT</span><b>OTHER / competing display</b></div><div><span>RESERVATION</span><b>Tuesday PM</b></div><div><span>WORK REMAINING</span><b>${s.other} units</b></div><div><span>HANDOFF</span><b>${s.otherDone===null?'Not complete':E.DAYS[s.otherDone]}</b></div></div><p class="legend">Authored scenario state; this job has no separate supplier payment attempt.</p>`;
 if(s.view==='Control')return `<h3>Display job / production control</h3><p>The producer assigns the shared staff. Capacity not assigned to C-07 works on this reservation.</p><p class="legend">The Tuesday deadline is fixed in this scenario. C-07's client extension does not move it.</p>`;
 return `<h3>Display job / ${2-s.crew} unit per interval</h3><div class="info-grid"><div><span>SHARED CAPACITY</span><b>2 units total</b></div><div><span>ASSIGNED TO C-07</span><b>${s.crew} units</b></div><div><span>REMAINING HERE</span><b>${s.other} units</b></div><div><span>DEADLINE</span><b>Tuesday PM</b></div></div>`;
}

if(s.view==='Cash')return `<h3>Cash has a direction.</h3><table><tbody>${row('Opening bank cash',cash(C.startingCash))}${s.ledger.map(e=>row(`${e.id} · ${e.label}`,`${e.amount>0?'+':''}${cash(e.amount)}`)).join('')}${row('Posted balance',cash(s.cash))}${row('Still reserved',cash(E.committed(s)))}${row('Available after reserves',cash(E.available(s)))}</tbody></table><p class="legend">The campaign ceiling and client receivable are excluded from bank cash.</p>`;
if(s.view==='Information')return `<h3>What is known now</h3><div class="info-grid"><div><span>PAYMENT SNAPSHOT</span><b>${s.documents.includes('v2')?'v2 / Paid / saved Tuesday':s.documents.includes('v1')?'v1 / Scheduled':'No platform record yet'}</b></div><div><span>BANK</span><b>${s.returned?'P-04 debit and equal return':s.turn>=2&&s.plan==='supplier'?'P-04 debit posted':'No P-04 debit'}</b></div><div><span>RECIPIENT</span><b>${s.supplierSettled?'Receipt confirmed':s.requests.recipient?.status==='received'?'P-04 not received':'Not confirmed'}</b></div><div><span>OBLIGATION</span><b>${s.plan!=='supplier'?'No O-19 in this plan':s.supplierSettled?'O-19 resolved':'O-19 remains open'}</b></div></div><p class="legend">Open the saved records below. A later event does not rewrite an earlier snapshot.</p>`;
if(s.view==='Control')return `<h3>Who can do what</h3><table><tbody>${row('Production / you','Plan, place, staff, request')}${row('Finance','Approve one reissue')}${row('Supplier S-08','Confirm receipt; release component')}${row('Client','Accept revised handoff')}</tbody></table><p class="legend">${s.approved?'Finance approval received.':s.requests.approval?'Finance approval pending.':'No reissue approval held.'} A bank return alone does not grant authority to pay again.</p>`;
return `<h3>Two units per interval</h3><div class="info-grid"><div><span>C-07 ALLOCATION</span><b>${s.crew} unit${s.crew===1?'':'s'} / interval</b></div><div><span>DISPLAY JOB ALLOCATION</span><b>${2-s.crew} unit / interval</b></div><div><span>DISPLAY DEADLINE</span><b>Tue PM / ${s.other} units remain</b></div><div><span>STAFF COST</span><b>$6,000 payroll on Fri AM</b></div></div><p class="legend">Payroll is fixed in this scenario. Assigning both units to C-07 uses the capacity already reserved for the display job.</p>`;
}
function decisions(){
let out=!s.started?`<h3>Choose how it gets made.</h3><p>Complete C-07 by Thursday PM while protecting the display job’s Tuesday handoff. Plans and bay placement can change until the first interval.</p><div class="plans">${button('<b>Make in-house</b><span>$4,000 materials · 6 fabrication + 2 check-and-pack units</span><small>USES SHARED STAFF / NO SUPPLIER PAYMENT</small>','plan','internal',`aria-pressed="${s.plan==='internal'}"`)}${button('<b>Commission S-08</b><span>$12,000 supplier obligation · 2 check-and-pack units in-house</span><small>LESS STAFF TIME / RELEASE DEPENDS ON PAYMENT</small>','plan','supplier',`aria-pressed="${s.plan==='supplier'}"`)}</div>`:`<h3>${E.stage(s)}</h3><p>${s.plan==='internal'?'In-house plan':s.substitute?'Supplier plan + substitute':'Supplier S-08 plan'} · ${s.bay==='dock'?'near-dock bay':'shared-floor bay'}. ${s.delivered!==null?'Client invoice raised; payment is outside this episode.':'Handoff promised '+E.DAYS[s.promise]+'.'}</p>`;
out+=`<div class="staff"><label>CAPACITY / C-07</label><div class="staff-options">${button('1 unit / shared','crew',1,`aria-pressed="${s.crew===1}" ${s.finished?'disabled':''}`)}${button('2 units / concentrated','crew',2,`aria-pressed="${s.crew===2}" ${s.finished?'disabled':''}`)}</div><small>${s.other?`${s.other} units remain on the display job. Due Tue PM.`:'Display job finished '+E.DAYS[s.otherDone]+'.'} Staff can be reassigned between intervals.</small></div>`;
if(s.returned&&!s.supplierSettled&&!s.finished){out+=`<div class="response-list"><p><b>The bank returned the funding.</b> The saved Paid label is still on the desk. Establish what happened before authorizing a new attempt.</p>`;
for(const[type,label,wait]of[['processor','Trace P-04',1],['recipient','Ask S-08 for confirmation',2],['invoice','Request invoice export',1]]){const r=s.requests[type];out+=button(`${label}<small>${r?r.status==='received'?'RESPONSE ON THE DESK':`DUE ${E.DAYS[r.due]||'NEXT SHIFT'}`:`${wait} INTERVAL${wait>1?'S':''} / NO CASH COST`}</small>`,'request',type,r?'disabled':'');}
if(['processor','recipient'].some(k=>s.requests[k]?.status==='received'))out+=button(`Request finance approval<small>${s.approved?'APPROVED':s.requests.approval?'PENDING':'1 INTERVAL / O-19 ONLY'}</small>`,'request','approval',s.requests.approval?'disabled':'');
if(s.approved)out+=button(`Reissue O-19 / $12,000<small>${s.reissue?'P-05 SENT / RECEIPT PENDING':'NEW ATTEMPT P-05 / RECEIPT NEXT INTERVAL'}</small>`,'reissue',undefined,s.reissue?'disabled':'');
out+=button(`Build a substitute<small>${s.substitute?'IN PRODUCTION / O-19 STILL OPEN':'$1,500 OPTION + $4,000 MATERIALS / 3 STAFF UNITS'}</small>`,'substitute',undefined,s.substitute?'disabled':'');out+='</div>';}
if(s.started&&s.delivered===null&&!s.finished)out+=`<div class="response-list">${button(`Request Friday handoff<small>${s.delayApproved?'ACCEPTED / ORIGINAL PROMISE RETAINED':s.requests.delay?'REPLY PENDING':'CLIENT REPLY IN 1 INTERVAL'}</small>`,'request','delay',s.requests.delay?'disabled':'')}</div>`;
return out;
}
const labels={terms:['C-07','Work order','memo'],bank:['BANK','Bank extract','strip'],v1:['P-04 / V1','Scheduled','carbon'],v2:['P-04 / V2','Paid snapshot','carbon'],return:['P-04','Return notice','strip'],processor:['TRACE','Processor reply','memo'],recipient:['S-08','Supplier reply','memo'],invoice:['O-19','Invoice export',''],approval:['FINANCE','Reissue authority','memo'],delay:['CLIENT','Revised handoff','memo'],reissue:['P-05','New attempt','carbon'],'reissue-receipt':['S-08','P-05 received','strip'],'ordinary-receipt':['S-08','P-04 received','strip'],pool:['B-09','Batch + receipts','strip'],client:['C-07','Client invoice','']};
function render(){
const prior=document.activeElement,focusAction=prior?.dataset.action,focusValue=prior?.dataset.value;
$('mode').value=s.mode;$('mode').disabled=s.started;$('date').textContent=E.DAYS[s.turn];$('interval').textContent=s.finished?'Run complete':s.started?'Interval '+s.turn+' / 12':'Planning';$('cash').textContent=cash(s.cash);$('reserved').textContent=cash(E.committed(s));$('available').textContent=cash(E.available(s));$('receivable').textContent=s.delivered!==null?cash(C.fee):'$0';
$('decisions').innerHTML=decisions();$('view-panel').innerHTML=view();
for(const el of document.querySelectorAll('[data-view]'))el.setAttribute('aria-pressed',el.dataset.view===s.view);
for(const el of document.querySelectorAll('[data-select]'))el.setAttribute('aria-pressed',el.dataset.select===s.selection);
for(const el of document.querySelectorAll('[data-bay]')){el.setAttribute('aria-pressed',el.dataset.bay===s.bay);el.disabled=s.started;}
$('advance').disabled=!s.plan||s.finished;$('auto').disabled=!s.plan||s.finished;
const records=['terms',...(s.ledger.length?['bank']:[]),...s.documents,...(s.delivered!==null?['client']:[])];
$('record-tray').innerHTML=[...new Set(records)].map(id=>{const l=labels[id];return `<button class="record-tab ${l[2]}" data-doc="${id}"><small>${l[0]}</small><b>${l[1]}</b><small>OPEN RECORD ↗</small></button>`;}).join('');
$('event-log').innerHTML=s.events.length?s.events.slice().reverse().map(e=>`<li><time>${E.DAYS[e.turn]}</time><span>${e.text}</span></li>`).join(''):'<li><time>Mon AM</time><span>Two staff units available. No plan committed.</span></li>';
$('pool-control').innerHTML=s.turn<6?'<p>Arrives Thursday AM. Use it to compare a routine payment with the exception.</p>':`<p>One bank debit: $2,000. Two allocations: $1,200 and $800. Both recipients confirm receipt.</p><p style="margin-top:12px">How much cash left the bank?</p><div class="answers">${[200000,400000,120000].map(n=>button(cash(n),'poolAnswer',n,`aria-pressed="${s.poolAnswer===n}"`)).join('')}</div>${s.poolAnswer!==null?`<p class="feedback">${s.poolAnswer===200000?'Correct. The two allocations describe the one bank debit; adding them again would double count the cash movement.':'Compare the bank debit with its allocations. The allocations divide the payment; they are not additional debits.'}</p>`:''}<p>${button('Open B-09 and receipts','open','pool')}</p>`;
$('outcome').hidden=!s.finished;if(s.finished){const o=E.outcome(s);$('outcome').innerHTML=`<div class="outcome-box"><header><span class="folio">RUN RECEIPT / ${s.mode==='ordinary'?'ORDINARY CONTROL':'FULL EPISODE'}</span><h2>${o.metPromise?'Handoff made.':'The handoff slipped.'}</h2></header><div class="outcome-grid"><div><small>C-07 DELIVERY</small><strong>${o.delivery}</strong></div><div><small>ORIGINAL THURSDAY PROMISE</small><strong>${o.originalPromiseMet?'Kept':'Missed'}</strong></div><div><small>DISPLAY RESERVATION</small><strong>${o.otherOnTime?'Protected':'Missed'}</strong></div><div><small>POSTED CASH</small><strong>${cash(o.posted)}</strong></div><div><small>STILL RESERVED</small><strong>${cash(o.committed)}</strong></div><div><small>CLIENT RECEIVABLE / NOT CASH</small><strong>${cash(o.receivable)}</strong></div></div><p>${o.obligation}. ${o.batch}. ${s.substitute?'The substitute preserved an operational route; it did not erase the supplier obligation.':''}</p><div class="actions">${button('Try the other plan','replay')}${button('Run the ordinary control','ordinary')}<button id="outcome-export">Download run receipt ↓</button></div></div>`;}
hits=window.MMTEpisodeScene.draw($('map'),s,t);$('motion').textContent=scenery?'Pause scenery':'Play scenery';
if(focusAction&&!prior.isConnected){const target=[...document.querySelectorAll('[data-action]')].find(b=>b.dataset.action===focusAction&&b.dataset.value===focusValue);(target&&!target.disabled?target:$('advance')).focus({preventScroll:true});}
}
function documentBody(id){let title=labels[id][1],cls=labels[id][2],head=labels[id][0],body='',note='',tag='FICTIONAL SCENARIO / LIVE RUN';
if(id==='terms'){body=`<h3>Fabricated component</h3><div class="big">$100,000 <small>ceiling</small></div><table>${row('Client fee to invoice on handoff','$24,000')}${row('Original handoff','W3 Thu PM')}${row('Opening bank cash','$40,000')}${row('Shared capacity','2 units / interval')}${row('Competing display job','3 units / due Tue PM')}${row('Staff payroll / Friday AM','$6,000')}${row('Routine batch / Thursday AM','$2,000')}</table><p>The campaign ceiling is a planning limit, not a transfer. No client cash receipt is modeled. Material purchase is cash; staff effort draws on fixed payroll.</p>`;note='Select a plan and a work bay, then allocate staff. One interval is half a workday. Plans and placement lock on the first interval; staffing remains adjustable. Near-dock handoff takes one interval after work and supplier release are ready; shared-floor handoff takes two. These timing and cost rules are authored simulation assumptions.';}
else if(id==='bank'){body=`<h3>Posted entries</h3><div class="entry">OPENING BALANCE<strong>$40,000</strong></div>${s.ledger.map(e=>`<div class="entry">${e.id} / ${E.DAYS[e.turn]}<br>${e.label}<strong>${e.amount>0?'+':''}${cash(e.amount)}</strong></div>`).join('')}<div class="entry">CLOSING BALANCE<strong>${cash(s.cash)}</strong></div>`;note='Read direction and identity together. A debit and its equal return net to zero for that attempt. O-19 can remain due. Allocations inside B-09 are not additional bank entries.';}
else if(id==='v1'||id==='v2'){const paid=id==='v2';tag='SAVED FIXTURE / NEVER REWRITTEN';body=`<h3>${paid?'Paid':'Scheduled'}</h3><div class="big">$12,000</div><table>${row('Campaign','C-07')}${row('Obligation','O-19')}${row('Recipient','S-08')}${row('Payment attempt','P-04')}${row('Saved at',paid?'W3 Tue 10:02':'W3 Mon 15:20')}${row('Version',paid?'2':'1')}</table><p>Status as saved at the time shown.</p>`;note=paid?'This Tuesday snapshot predates the Wednesday return in the full episode. It establishes what this saved record displayed. It does not establish what the interface displayed after the return, or prove recipient settlement.':'This is the earlier version of the same payment attempt. It records scheduling, not a recipient receipt.';}
else if(id==='return'){body=`<h3>Funding returned</h3><div class="big">+$12,000</div><table>${row('Attempt','P-04')}${row('Obligation','O-19')}${row('Bank event','W3 Wed AM')}${row('Earlier funding debit','−$12,000')}${row('Net for this attempt','$0')}</table>`;note='This run has returned the funding. Request a processor trace or a recipient response to establish the link before finance authorizes another attempt. The return does not cancel the fabrication obligation.';}
else if(id==='pool'){body=`<h3>Batch B-09</h3><div class="big">−$2,000</div><table>${row('Bank debit','W3 Thu AM')}${row('O-20 allocation','$1,200')}${row('O-21 allocation','$800')}${row('O-20 recipient','Receipt confirmed')}${row('O-21 recipient','Receipt confirmed')}</table>`;note='This is a valid pooled payment. Its two allocations add to the one bank debit. The matching receipts provide a reason to close these obligations without inventing a discrepancy.';}
else if(id==='client'){body=`<h3>Campaign handoff</h3><div class="big">$24,000</div><table>${row('Campaign','C-07')}${row('Delivery',E.DAYS[s.delivered])}${row('Invoice state','Issued')}${row('Cash received','$0')}</table>`;note='Revenue invoiced is not cash received. Collection is outside this episode, so the receivable stays separate from the bank balance.';}
else {const text={processor:'The $12,000 return is linked to attempt P-04. No later settlement attempt is supplied in the fixed record set.',recipient:'S-08 confirms that attempt P-04 was not received. The component is fabricated but remains held against the open $12,000 obligation O-19.',invoice:'Obligation O-19: fabrication component for C-07. Amount: $12,000. Exported invoice information does not establish receipt of payment.',approval:'Finance authorizes one $12,000 reissue against O-19, following the received trace or recipient response. Use a new attempt ID: P-05.',delay:'The client accepts a revised handoff of W3 Friday PM. The original W3 Thursday PM promise remains in the shift log.',reissue:'A new, player-authorized attempt P-05 has debited $12,000. Recipient confirmation is due next interval. This new attempt does not change the saved P-04 records.','reissue-receipt':'S-08 confirms receipt of the $12,000 P-05 reissue. O-19 is resolved and the component is released.','ordinary-receipt':'S-08 confirms receipt of the original $12,000 P-04 payment. O-19 is resolved and the component is released.'}[id];body=`<h3>${title}</h3><p>${text}</p>`;note=['approval','delay','reissue','reissue-receipt','ordinary-receipt'].includes(id)?'This response is produced by the fictional simulation. It is not an additional historical source, and it does not modify the fixed saved snapshots.':'This response belongs to the fictional practice record set. It describes one object or attempt; it is not a conclusion about the historical case.';}
return {title,html:`<article class="paper ${cls}"><div class="stamp"><span>${head}</span><span>${tag}</span></div>${body}<footer>MAD MONEY TYCOON / EPISODE 01 / INVENTED VALUES</footer></article><aside class="annotation"><b>READING THIS RECORD</b><p>${note}</p>${['v1','v2'].includes(id)?`<div class="doc-versions">${s.documents.filter(x=>['v1','v2'].includes(x)).map(x=>`<button data-doc="${x}" aria-pressed="${id===x}">${x.toUpperCase()}</button>`).join('')}</div>`:''}<p>Simulation is paused while this desk is open.</p><button data-close>Return to the same view ↙</button></aside>`};
}
function openDoc(id){stop();doc=id;const d=documentBody(id);$('doc-title').textContent=d.title;$('doc-content').innerHTML=d.html;if(!$('desk').open)$('desk').showModal();}
function closeDoc(){doc=null;$('desk').close();last=0;}
function exportRun(){const data={title:'Mad Money Tycoon / Episode 01',scope:'Entirely fictional simulation; not historical evidence',modelRevision:C.revision,config:C,mode:s.mode,outcome:E.outcome(s),state:s};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`mmt-episode-01-${s.mode}-${s.turn}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function reset(mode=s.mode,plan=null){stop();s=E.initial(mode);if(plan)s=E.reduce(s,{type:'plan',value:plan});persist();render();window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.doc){openDoc(b.dataset.doc);return;}if(b.hasAttribute('data-close')){closeDoc();return;}if(b.dataset.view)dispatch({type:'view',value:b.dataset.view});if(b.dataset.select)dispatch({type:'select',value:b.dataset.select});if(b.dataset.bay)dispatch({type:'bay',value:b.dataset.bay});if(b.dataset.action){const type=b.dataset.action;if(type==='open'){openDoc(b.dataset.value);return;}if(type==='replay'){reset(s.mode,s.plan==='internal'?'supplier':'internal');return;}if(type==='ordinary'){reset('ordinary');return;}dispatch({type,value:['crew','poolAnswer'].includes(type)?Number(b.dataset.value):b.dataset.value});}if(b.id==='outcome-export')exportRun();});
$('advance').onclick=()=>dispatch({type:'advance'});$('auto').onclick=()=>{if(auto){stop();return;}auto=setInterval(()=>dispatch({type:'advance'}),2400);$('auto').textContent='Pause schedule';};$('motion').onclick=()=>{scenery=!scenery;render();};$('new-run').onclick=()=>{if(!s.started||s.finished||confirm('Start a new run? Export the current run first if you want to keep it.'))reset();};$('mode').onchange=e=>reset(e.target.value);$('terms-link').onclick=e=>{e.preventDefault();openDoc('terms');};$('export-run').onclick=exportRun;$('close-desk').onclick=closeDoc;$('desk').addEventListener('close',()=>{doc=null;last=0;});
$('map').onclick=e=>{if(s.started)return;const r=e.target.getBoundingClientRect(),x=(e.clientX-r.left)*640/r.width,y=(e.clientY-r.top)*320/r.height;const hit=hits.map(h=>({...h,d:Math.hypot(h.p[0]-x,h.p[1]-y)})).sort((a,b)=>a.d-b.d)[0];if(hit?.d<65)dispatch({type:'bay',value:hit.id});};
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){scenery=false;render();}});document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden)stop();});
function frame(now){if(last&&scenery&&!doc&&!document.hidden){t+=Math.min(.08,(now-last)/1000);window.MMTEpisodeScene.draw($('map'),s,t);}last=now;requestAnimationFrame(frame);}render();requestAnimationFrame(frame);
window.MMTGame={get state(){return JSON.parse(JSON.stringify(s));},dispatch,reset,openDoc,closeDoc,stop,render,get sceneTime(){return t;},setSceneTime(value){t=value;scenery=false;render();},get playing(){return !!auto;}};
})();
