(()=>{'use strict';
const D=window.BASECAMP,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels=Object.fromEntries(Object.entries(D.types).map(([k,v])=>[k,v.label]));
let filter='all',stage='all',query='',lastFocus=null;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let motionOn=!reduced.matches;
const observer=new IntersectionObserver(items=>{for(const item of items){const im=item.target;im.dataset.visible=String(item.isIntersecting);const target=motionOn&&item.isIntersecting?im.dataset.motion:im.dataset.poster;if(target&&im.getAttribute('src')!==target)im.src=target;}},{threshold:.05});
function observeMedia(){observer.disconnect();document.querySelectorAll('img[data-motion]').forEach(im=>observer.observe(im));document.querySelectorAll('[data-motion-toggle]').forEach(b=>{b.textContent=motionOn?'pause gifs':'play gifs';b.setAttribute('aria-pressed',String(motionOn))});}
function setMotion(value){motionOn=value;document.querySelectorAll('img[data-motion]').forEach(im=>{im.src=motionOn&&im.dataset.visible==='true'?im.dataset.motion:im.dataset.poster});observeMedia();}
reduced.addEventListener('change',ev=>setMotion(!ev.matches));
const entry=id=>D.entries.find(e=>e.id===id),src=id=>D.sources.find(s=>s.id===id);
const link=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(label)} ↗</a>`;
const inspect=(id,label)=>`<button class="text-button" data-item="${id}">${esc(label||entry(id).title)}</button>`;
const loop=e=>e.loop.length?`<div class="mini-loop" aria-label="activity sequence">${e.loop.map((v,i)=>(i?'<i aria-hidden="true">→</i>':'')+'<span>'+esc(v)+'</span>').join('')}</div>`:'';
const mediaImage=m=>`<img src="${esc(m.poster)}" ${m.motion?`data-poster="${esc(m.poster)}" data-motion="${esc(m.motion)}"`:''} alt="${esc(m.caption)}" loading="lazy">`;
const thumb=e=>`<button class="thumb" data-item="${e.id}" aria-label="inspect ${esc(e.title)}">${mediaImage(e.media[0])}</button>`;
const preview=(e,m)=>`<figure class="entry-preview"><button data-item="${e.id}" aria-label="inspect ${esc(e.title)}">${mediaImage(m)}</button><figcaption><span>${esc(m.kind)}</span>${esc(m.caption)}</figcaption></figure>`;
$('.index-strip').innerHTML=Object.entries(labels).map(([k,v])=>`<a href="#catalogue?type=${k}">${v}<span>${String(D.entries.filter(e=>e.type===k).length).padStart(2,'0')}</span></a>`).join('');
$('#overview-count').textContent=`${D.entries.length} records · ${D.mechanisms.length} interaction studies.`;
const plays=D.entries.filter(e=>e.type==='playables');
$('#playable-list').innerHTML=plays.map(e=>`<article class="playable-row">${thumb(e)}<div><div class="kicker"><span>${e.id}</span><span>${esc(e.revision)}</span></div><h3>${inspect(e.id)}</h3><p>${esc(e.lead)}</p></div><div>${loop(e)}<div class="question-small">${esc(e.facts['main question'])}</div></div></article>`).join('');
$('#direction-forks').innerHTML=['e04','e05','e13'].map(id=>{const e=entry(id);return `<button class="fork" data-item="${id}"><span class="mono">${e.id} / ${e.implementation}</span><strong class="fork-title">${esc(e.title)}</strong><span class="fork-description">${esc(e.question)}</span><span class="arrow" aria-hidden="true">↗</span></button>`}).join('');
$('#filters').innerHTML=['all',...Object.keys(labels)].map(k=>`<button data-filter="${k}" aria-pressed="${k==='all'}">${labels[k]||'all types'}</button>`).join('');
function renderCards(){const list=D.entries.filter(e=>(filter==='all'||e.type===filter)&&(stage==='all'||e.implementation===stage)&&JSON.stringify([e.title,e.lead,e.verb,e.question,e.scope,e.limit,e.facts,e.loop]).toLowerCase().includes(query.toLowerCase()));
$('#results').textContent=`${list.length} of ${D.entries.length} entries`;$('#empty').hidden=!!list.length;
$('#cards').innerHTML=list.map(e=>`<article class="card"><div class="card-top"><span>${e.id} / ${labels[e.type]}</span><span class="state ${e.implementation}">${e.implementation}</span></div><div class="card-body ${e.image?'has-image':''}"><div><h3>${inspect(e.id)}</h3><p>${esc(e.lead)}</p></div>${e.media?preview(e,e.media[0]):''}</div><div class="card-bottom"><span>${esc(e.verb)}</span><button data-item="${e.id}" aria-label="inspect ${esc(e.title)}">↗</button></div></article>`).join('');
document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));$('#stage').value=stage;observeMedia();}
$('#mechanisms').innerHTML=D.mechanisms.map(m=>`<article class="mechanism"><span class="mono">${m.id}</span><h3>${esc(m.title)}</h3><ul>${m.alternatives.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><p>${esc(m.scope)}</p>${m.sources.map(id=>link(src(id).excerpt,id+' · '+src(id).title)).join(' ')}</article>`).join('');
$('#type-definitions').innerHTML=Object.entries(D.types).map(([id,t])=>`<article class="type-definition"><span class="mono">${String(D.entries.filter(e=>e.type===id).length).padStart(2,'0')} entries</span><h2>${esc(t.label)}</h2><p>${esc(t.definition)}</p><a href="#catalogue?type=${id}">browse →</a></article>`).join('');
$('#stage-definitions').innerHTML=Object.entries(D.implementationStates).map(([id,text])=>`<article><h3><span class="state ${id}">${id}</span></h3><p>${esc(text)}</p></article>`).join('');
$('#relationships').innerHTML=D.relations.map(rel=>`<div class="relationship">${inspect(rel.from)}<span class="relation-type">${rel.type} <span aria-hidden="true">→</span><small>${esc(rel.label)}</small></span>${inspect(rel.to)}</div>`).join('');
$('#decisions').innerHTML=D.decisions.map(d=>`<article class="decision"><div class="card-top"><span>${d.id}</span><span class="state outlined">${d.state}</span></div><div><h3>${esc(d.title)}</h3><p>${esc(d.definition)}</p><p class="decision-question">${esc(d.question)}</p></div></article>`).join('');
$('#compare-cards').innerHTML=plays.map(e=>`<article class="compare-card">${thumb(e)}<h3>${inspect(e.id)}</h3><p class="mono">${esc(e.revision)}</p><p>${esc(e.question)}</p></article>`).join('');
$('#comparison').innerHTML='<thead><tr><th scope="col">rule</th>'+plays.map(e=>`<th scope="col">${esc(e.title)}</th>`).join('')+'</tr></thead><tbody>'+Object.keys(plays[0].facts).map(k=>`<tr><th scope="row">${esc(k)}</th>${plays.map(e=>`<td>${esc(e.facts[k])}</td>`).join('')}</tr>`).join('')+'</tbody>';
$('#gaps').innerHTML=D.gaps.map(g=>`<div class="gap"><h3>${esc(g.title)}</h3><p>${esc(g.basis)}</p></div>`).join('');
$('#branches').innerHTML=D.branches.map(b=>`<article class="branch-record"><p class="mono">${esc(b.name)} / ${b.revision}</p><p>${esc(b.role)}</p><div>${b.entries.map(id=>inspect(id)).join(' · ')}</div>${link(b.url,'revision source')}</article>`).join('');
$('#source-register').innerHTML=D.sources.map(s=>`<article class="source-row" id="${s.id}"><span class="mono">${s.id}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.revision)}</p></div><div><p>${esc(s.points[0])}</p></div><div>${link(s.excerpt,'design extract')}${s.url?'<br>'+link(s.url,'original source'):''}</div></article>`).join('');
$('#versions').innerHTML=D.versions.map(v=>link(v.url,'design '+v.version)).join('');
function showEntry(id){const e=entry(id);if(!e)return;if(!$('#detail').open)lastFocus=document.activeElement;
$('#detail-meta').textContent=`${e.id} / ${labels[e.type]} / ${e.implementation}`;
const related=D.relations.filter(r=>r.from===id||r.to===id);
$('#detail-body').innerHTML=`<h2 id="detail-title">${esc(e.title)}</h2><p class="lead">${esc(e.lead)}</p>${loop(e)}${e.media.map(m=>`<figure class="entry-preview detail-preview">${mediaImage(m)}<figcaption><span>${esc(m.kind)}</span>${esc(m.caption)}${m.motion?'<button class="media-toggle" data-motion-toggle aria-pressed="'+motionOn+'">'+(motionOn?'pause gifs':'play gifs')+'</button>':''}<a href="${esc(m.motion||m.poster)}" target="_blank" rel="noopener">open ${m.motion?'gif':'image'} ↗</a></figcaption></figure>`).join('')}<dl><dt>activity</dt><dd>${esc(e.verb)}</dd><dt>test question</dt><dd>${esc(e.question)}</dd><dt>scope</dt><dd>${esc(e.scope)}</dd><dt>availability</dt><dd>${esc(e.availability)}</dd><dt>revision</dt><dd>${esc(e.revision)}</dd></dl><div class="limit"><span>unresolved scope</span>${esc(e.limit)}</div>${related.length?'<div class="detail-relations"><h3>relationships</h3>'+related.map(r=>`<p>${inspect(r.from)} <span>${r.type} →</span> ${inspect(r.to)}</p>`).join('')+'</div>':''}${e.links?.length?'<div class="entry-links">'+e.links.map(l=>link(l.url,l.label)).join('')+'</div>':''}<div class="detail-sources"><h3>sources</h3>${e.sources.map(id=>link(src(id).excerpt,src(id).id+' · '+src(id).title)).join('')}</div>`;
if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;$('#close-detail').focus();observeMedia();}
function route(){const [name,qs]=(location.hash.slice(1)||'overview').split('?');const page=['overview','catalogue','structure','compare','sources'].includes(name)?name:'overview';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==page);document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.title=page+' · mad money basecamp · wip';const params=new URLSearchParams(qs||'');if(page==='catalogue'){const aliases={precursors:'presentations',directions:'concepts',open:'agency'};const type=params.get('type')||aliases[params.get('family')]||params.get('family');filter=Object.hasOwn(labels,type)?type:'all';stage='all';query='';$('#search').value='';renderCards()}if($('#detail').open)$('#detail').close();window.scrollTo(0,0);if(params.has('item'))showEntry(params.get('item'));observeMedia();}
document.addEventListener('click',ev=>{if(ev.target.closest('[data-motion-toggle]')){setMotion(!motionOn);return}const download=ev.target.closest('a[download]');if(download&&['catalogue.json','catalogue.md'].includes(download.getAttribute('href'))){ev.preventDefault();const name=download.getAttribute('href'),contents=name.endsWith('.json')?JSON.stringify(D,null,2)+'\n':window.BASECAMP_MARKDOWN,url=URL.createObjectURL(new Blob([contents],{type:name.endsWith('.json')?'application/json':'text/markdown'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);return}const item=ev.target.closest('[data-item]');if(item){showEntry(item.dataset.item);return}const source=ev.target.closest('[data-source]');if(source){window.open(src(source.dataset.source).excerpt,'_blank','noopener');return}const f=ev.target.closest('[data-filter]');if(f){filter=f.dataset.filter;renderCards()}});
$('#search').addEventListener('input',ev=>{query=ev.target.value;renderCards()});$('#stage').onchange=ev=>{stage=ev.target.value;renderCards()};$('#clear-search').onclick=()=>{filter='all';stage='all';query='';$('#search').value='';renderCards()};$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()});$('#export-menu').onclick=()=>$('#exports').showModal();$('#close-export').onclick=()=>$('#exports').close();$('#print').onclick=()=>{$('#exports').close();window.print()};window.addEventListener('hashchange',route);renderCards();route();window.BASECAMP_READY=true;
})();
