const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const A='latest-design/assets/';
const scenes={campus:'campus.png',party:'campus-party.png',social:'campus-social.png',garden:'campus-garden.png'};
const questions={work:['WHAT IS HAPPENING; WHAT BLOCKS IT?','Visible activity does not establish revenue or cash receipt.'],cash:['WHAT MOVED, AND HOW FAR IS IT SUPPORTED?','A commitment is not a receipt; Paid is not universal settlement truth.'],information:['WHICH RECORD, VERSION AND SOURCE?','A saved label remains inside its dated record.'],control:['WHO COULD DO WHICH ACTION THEN?','Capability does not prove execution.'],people:['WHO SUPPLIES WORK AND BEARS INTERRUPTION?','Modeled strain does not establish a real person’s feelings.']};
const objects=[
{id:'boerum',name:'Boerum studio',type:'SITE · B-01',x:202,y:116,preview:'boerum-cutaway.png',inside:'boerum-cutaway.png',copy:'Creative review and a shared production shop occupy this office-derived site.',facts:['Provides','Creative review + shared shop','Pressure','Two jobs need the same 16 hours']},
{id:'porter',name:'Porter hall',type:'SITE · B-02',x:415,y:217,preview:'porter-cutaway.png',inside:'porter-cutaway.png',copy:'The production hall supports fabrication and the physical service handoff.',facts:['Provides','Fabrication + loading','Route','Voila service edge']},
{id:'johnson',name:'266 Johnson',type:'SITE · B-03',x:488,y:105,preview:'johnson-cutaway.png',inside:'johnson-cutaway.png',copy:'Yellow-brick frontage, orange internal stair, white birch and office cat.',facts:['Provides','Accounts + coordination','Status','Interior exposed']},
{id:'campaign',name:'Campaign C-07',type:'PROJECT · C-07',x:304,y:179,preview:'campus-party.png',inside:'campus-party.png',copy:'A fictional $100,000 product-launch commission with a Thursday handoff.',facts:['Budget','Ceiling · $100,000','Deliverable','Fabricated component O-19']},
{id:'supplier',name:'Supplier S-08',type:'SUPPLIER · S-08',x:548,y:270,preview:'voila.png',inside:'voila.png',copy:'An external fabrication option with a two-day lead and a physical delivery.',facts:['Obligation','$12,000','Handoff','Thursday · Porter service edge']}
];
const S={view:'work',scene:'campus',selected:'boerum',interior:false,motion:true,plan:null,step:0,t:0};
const cv=$('#park'),c=cv.getContext('2d'),imgs={};Object.entries(scenes).forEach(([k,v])=>{let i=new Image;i.src=A+v;imgs[k]=i});
function draw(){let im=imgs[S.scene];if(im.complete)c.drawImage(im,0,0,640,360);else{c.fillStyle='#bdd5aa';c.fillRect(0,0,640,360)}if(S.view!=='work'){c.fillStyle=S.view==='information'?'#fff7fb66':'#ffffff38';c.fillRect(0,0,640,360)}if(S.view==='cash')line('campaign','supplier','#294b78');if(S.view==='control')line('campaign','johnson','#171719');if(S.view==='people')line('boerum','porter','#f17a47');if(S.view==='information')line('campaign','johnson','#f1b1ca');objects.forEach(mark);if(S.motion&&!matchMedia('(prefers-reduced-motion:reduce)').matches){let x=510+Math.sin(S.t*.018)*18;c.fillStyle='#171719';c.fillRect(x,281,14,6);c.fillStyle='#f2b43c';c.fillRect(x+2,277,10,5);S.t++}requestAnimationFrame(draw)}
function line(a,b,color){a=objects.find(o=>o.id===a);b=objects.find(o=>o.id===b);c.save();c.strokeStyle=color;c.lineWidth=2;c.setLineDash(S.view==='information'?[4,3]:[]);c.beginPath();c.moveTo(a.x,a.y);c.lineTo((a.x+b.x)/2,a.y);c.lineTo((a.x+b.x)/2,b.y);c.lineTo(b.x,b.y);c.stroke();c.restore()}
function mark(o){let active=o.id===S.selected;c.fillStyle='#171719';c.fillRect(o.x-6,o.y-6,12,12);c.fillStyle=active?'#51eb7b':S.view==='cash'?'#294b78':S.view==='information'?'#f1b1ca':'#fff';c.fillRect(o.x-4,o.y-4,8,8);if(active){c.strokeStyle='#171719';c.strokeRect(o.x-9,o.y-9,18,18)}}
function pick(e){let r=cv.getBoundingClientRect(),x=(e.clientX-r.left)*640/r.width,y=(e.clientY-r.top)*360/r.height,best=null,d=24;objects.forEach(o=>{let n=Math.hypot(o.x-x,o.y-y);if(n<d){d=n;best=o}});return best}
function select(id){let o=objects.find(o=>o.id===id);if(!o)return;S.selected=id;$('#object-type').textContent=o.type;$('#object-title').textContent=o.name;$('#object-copy').textContent=o.copy;$('#object-preview').src=A+(S.interior?o.inside:o.preview);$('#object-facts').innerHTML=`<dt>${o.facts[0]}</dt><dd>${o.facts[1]}</dd><dt>${o.facts[2]}</dt><dd>${o.facts[3]}</dd>`;$('#object-action').textContent=id==='campaign'?'OPEN C-07 WORK PLAN':id==='supplier'?'COMPARE MAKE / BUY':'INSPECT ACTIVE WORK';renderObjects();save()}
function renderObjects(){$('#objects').innerHTML=objects.map(o=>`<button data-object="${o.id}" class="${o.id===S.selected?'active':''}">■ ${o.name}</button>`).join('');$$('[data-object]').forEach(b=>b.onclick=()=>select(b.dataset.object))}
function setView(v){S.view=v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#view-question').textContent=questions[v][0];$('#limit').textContent=questions[v][1];$('#return-target').textContent=objects.find(o=>o.id===S.selected).name+' · '+v[0].toUpperCase()+v.slice(1)+' view';save()}
function setScene(s){S.scene=s;$$('[data-scene]').forEach(b=>b.classList.toggle('active',b.dataset.scene===s));save()}
function choosePlan(plan){S.plan=plan;$$('[data-plan]').forEach(b=>b.classList.toggle('selected',b.dataset.plan===plan));let make=plan==='internal';$('#consequence').innerHTML=`<small>CURRENT COMMITMENT</small><b>${make?'MAKE · SHARED SHOP':'BUY · SUPPLIER S-08'}</b><p>${make?'Reserve 12 of 16 shop hours and $6,400 internal cost.':'Create a $12,000 obligation; preserve all 16 shop hours.'}</p><button id="run">RUN INTERVAL →</button>`;$('#run').onclick=runInterval;$('#status').textContent=(make?'Internal capacity':'Supplier lead time')+' is now reserved. No cash movement has been asserted.';save()}
function runInterval(){if(!S.plan)return;let make=S.plan==='internal';if(S.step===0){S.step=1;$('#step-title').textContent='Inspect the first consequence';$('#step-copy').textContent='The component remains deliverable. Your plan changes the competing job and usable liquidity.';$('#capacity').textContent=make?'4 H':'16 H';$('#cash').textContent='$48,000';$('#consequence').innerHTML=`<small>AFTER MONDAY INTERVAL</small><b>${make?'O-19 READY WED · OTHER JOB QUEUED':'S-08 DUE THU · SHOP AVAILABLE'}</b><p>${make?'Four shop hours remain; the competing eight-hour job queues by four hours. Posted cash is unchanged.': '$12,000 is committed, leaving $36,000 usable; posted cash has not yet moved.'}</p><button id="run">KEEP OR REVISE →</button>`;$('#run').onclick=finishPlan;$('#status').textContent='Review the consequence. Choose the other plan to revise before committing.'}else finishPlan();progress();save()}
function finishPlan(){if(!S.plan)return;S.step=2;let make=S.plan==='internal';$('#step-title').textContent='Plan recorded · compare the tradeoff';$('#step-copy').textContent='Both plans meet C-07. Neither makes budget, obligation, posted cash and settlement interchangeable.';$('#consequence').innerHTML=`<small>THURSDAY REVIEW</small><b>${make?'DELIVERED · CAPACITY STRAIN':'DELIVERED · CASH COMMITTED'}</b><p>${make?'O-19 finished early; the competing job moved four hours later.':'S-08 delivered at Porter; the shop completed the competing job.'}</p><button id="run">TRY THE OTHER PLAN ↺</button>`;$('#run').onclick=()=>resetRun(make?'supplier':'internal');$('#status').textContent='Delivery succeeded. Try the other viable plan and compare what changed.';progress();save()}
function resetRun(plan){S.step=0;S.plan=null;$('#capacity').textContent='16 H';$('#cash').textContent='$48,000';$('#step-title').textContent='Choose how to fabricate O-19';$('#step-copy').textContent='Both plans can deliver the campaign. They commit different capacity, time and cash.';choosePlan(plan);progress()}
function progress(){$$('.progress i').forEach((i,n)=>i.classList.toggle('on',n<=S.step))}
const docInfo={invoice:['Obligation O-19','White ruled stock carries supplier, obligation, amount and terms.','An invoice establishes an obligation. It does not establish cash settlement with the recipient.'],'record-v2':['Saved platform record · V2','Pink carbon stock carries a dated record version.','V2 was saved Tuesday, before Wednesday’s return. Reopening it cannot establish a later platform status.'],'bank-events':['Bank-event strip','The perforated strip carries dated movement and the extract’s limits.','A debit followed by an equal return describes bank events; it does not by itself identify final recipient settlement.'],'player-note':['Player note','Ruled note stock preserves the player’s question and linked IDs.','An interpretation stays separate from the records supporting or conflicting with it.'],'form-reader':['Numbered form study','Fields, entity, period and revision remain explicit.','This fictional T-01 layout is unbound and is not evidence connected to C-07.']};
function openDocs(){S.motion=false;$('#motion').textContent='▶ PLAY MOTION';let o=objects.find(o=>o.id===S.selected);$('#return-target').textContent=o.name+' · '+S.view[0].toUpperCase()+S.view.slice(1)+' view';$('#document-desk').showModal()}
function setDoc(id){let d=docInfo[id];$$('[data-doc]').forEach(b=>b.classList.toggle('active',b.dataset.doc===id));$('#doc-image').src='latest-design/documents/'+id+'.png';$('#doc-title').textContent=d[0];$('#doc-caption').textContent=d[1];$('#doc-note').textContent=d[2]}
function toggleInterior(on){S.interior=on;$('#exterior').classList.toggle('active',!on);$('#interior').classList.toggle('active',on);let o=objects.find(o=>o.id===S.selected);$('#object-preview').src=A+(on?o.inside:o.preview);$('#object-status').textContent=on?'INTERIOR':'EXTERIOR';save()}
function save(){localStorage.setItem('mmt-design-012',JSON.stringify({view:S.view,scene:S.scene,selected:S.selected,interior:S.interior,plan:S.plan,step:S.step,motion:S.motion}))}
function load(){try{let d=JSON.parse(localStorage.getItem('mmt-design-012'));if(!d)return;Object.assign(S,d);if(!scenes[S.scene])S.scene='campus';if(!questions[S.view])S.view='work';if(!objects.some(o=>o.id===S.selected))S.selected='boerum'}catch(e){localStorage.removeItem('mmt-design-012')}}
function hardReset(){localStorage.removeItem('mmt-design-012');location.reload()}
let motionBeforeDocs=true;
cv.addEventListener('mousemove',e=>{let o=pick(e),tip=$('#map-label');if(!o){tip.hidden=true;return}let r=cv.getBoundingClientRect();tip.hidden=false;tip.textContent=o.name.toUpperCase();tip.style.left=e.clientX-r.left+10+'px';tip.style.top=e.clientY-r.top+10+'px'});cv.addEventListener('mouseleave',()=>$('#map-label').hidden=true);cv.addEventListener('click',e=>{let o=pick(e);if(o)select(o.id)});
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-scene]').forEach(b=>b.onclick=()=>setScene(b.dataset.scene));$$('[data-plan]').forEach(b=>b.onclick=()=>choosePlan(b.dataset.plan));$$('[data-doc]').forEach(b=>b.onclick=()=>setDoc(b.dataset.doc));
$('#motion').onclick=()=>{S.motion=!S.motion;$('#motion').textContent=S.motion?'Ⅱ PAUSE MOTION':'▶ PLAY MOTION';save()};$('#exterior').onclick=()=>toggleInterior(false);$('#interior').onclick=()=>toggleInterior(true);$('#object-action').onclick=()=>{if(S.selected==='supplier'||S.selected==='campaign')document.querySelector('.workbench').scrollIntoView({behavior:'smooth'});else toggleInterior(!S.interior)};
$('#docs').onclick=()=>{motionBeforeDocs=S.motion;openDocs()};$('#close-docs').onclick=()=>$('#document-desk').close();$('#document-desk').addEventListener('close',()=>{S.motion=motionBeforeDocs;$('#motion').textContent=S.motion?'Ⅱ PAUSE MOTION':'▶ PLAY MOTION';save()});$('#reset').onclick=hardReset;$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
document.addEventListener('keydown',e=>{if(e.target.closest('dialog'))return;let v={w:'work',c:'cash',i:'information',o:'control',p:'people'}[e.key.toLowerCase()];if(v)setView(v);if(e.key===' '){e.preventDefault();$('#motion').click()}});
objects.filter(o=>['boerum','porter','johnson'].includes(o.id)).forEach(o=>o.preview='campus.png');
load();setView(S.view);setScene(S.scene);select(S.selected);toggleInterior(S.interior);$('#motion').textContent=S.motion?'Ⅱ PAUSE MOTION':'▶ PLAY MOTION';let restoredPlan=S.plan,restoredStep=S.step;S.plan=null;S.step=0;if(restoredPlan){choosePlan(restoredPlan);if(restoredStep>=1)runInterval();if(restoredStep>=2)finishPlan()}progress();draw();

// Progression hardening after multi-loop gameplay test.
S.ranPlan=null;
choosePlan=function(plan){if(S.step>=2){S.step=0;S.ranPlan=null;$('#capacity').textContent='16 H';$('#cash').textContent='$48,000'}S.plan=plan;$$('[data-plan]').forEach(b=>b.classList.toggle('selected',b.dataset.plan===plan));let make=plan==='internal';$('#consequence').innerHTML=`<small>CURRENT COMMITMENT</small><b>${make?'MAKE · SHARED SHOP':'BUY · SUPPLIER S-08'}</b><p>${make?'Reserve 12 of 16 shop hours and $6,400 internal cost.':'Create a $12,000 obligation; preserve all 16 shop hours.'}</p><button id="run">${S.ranPlan&&S.ranPlan!==plan?'RUN REVISED PLAN →':'RUN INTERVAL →'}</button>`;$('#run').onclick=runInterval;$('#status').textContent=(make?'Internal capacity':'Supplier lead time')+' is reserved. No cash movement has been asserted.';progress();save()};
runInterval=function(){if(!S.plan)return;let make=S.plan==='internal';if(S.step===0||S.ranPlan!==S.plan){S.ranPlan=S.plan;S.step=1;$('#step-title').textContent='Inspect the first consequence';$('#step-copy').textContent='The component remains deliverable. Your plan changes the competing job and usable liquidity.';$('#capacity').textContent=make?'4 H':'16 H';$('#cash').textContent='$48,000';$('#consequence').innerHTML=`<small>AFTER MONDAY INTERVAL</small><b>${make?'O-19 READY WED · OTHER JOB QUEUED':'S-08 DUE THU · SHOP AVAILABLE'}</b><p>${make?'Four shop hours remain; the competing eight-hour job queues by four hours. Posted cash is unchanged.':'$12,000 is committed, leaving $36,000 usable; posted cash has not yet moved.'}</p><button id="run">KEEP OR REVISE →</button>`;$('#run').onclick=finishPlan;$('#status').textContent='Review the consequence. Choose the other plan to revise before committing.'}else finishPlan();progress();save()};
resetRun=function(plan){S.step=0;S.plan=null;S.ranPlan=null;$('#capacity').textContent='16 H';$('#cash').textContent='$48,000';$('#step-title').textContent='Choose how to fabricate O-19';$('#step-copy').textContent='Both plans can deliver the campaign. They commit different capacity, time and cash.';choosePlan(plan);progress()};
// Rebind any state restored before the hardened progression functions loaded.
if(S.plan){let p=S.plan,n=S.step;S.plan=null;S.step=0;S.ranPlan=null;choosePlan(p);if(n>=1)runInterval();if(n>=2)finishPlan()}
window.S=S;window.__MMT_VERSION='design-0.12-art-0.10';
